### ISSUE TITLE
Cancel Appointment via API

### ISSUE THREAD

**Issue by mirfan-sphealth** [redguava/cliniko-api#101]
Does the API support appointment cancellations. I have looked through the documentation but couldn't find anything specific. I have tried using the Update Appointment method but it doesn't seem to cancel the appointment.

**Comment by JohnColvin** [comment]
Hello!

It's not currently possible to cancel an appointment via the API. We should be adding this in the near future. I'll let you know when we do.

I think one of your co-workers had the same question a few days ago on our API google group. https://groups.google.com/a/redguava.com.au/forum/#!topic/cliniko-api/NsC7uv0ydY0

**Comment by JohnColvin** [comment]
Oops didn't mean to close

**Comment by mirfan-sphealth** [comment]
Thanks for the quick clarification. Please keep us posted when you guys decided to do it.

**Comment by bpinto** [comment]
Hey @mirfan-sphealth we just added it here https://github.com/redguava/cliniko-api/pull/107
