### ISSUE TITLE
Question regarding use and structure of Cliniko API authorization header. 

### ISSUE THREAD

**Issue by TM818** [redguava/cliniko-api#102]
We're converting our code to use the Authorization header instead of passing the API key in the URL as recommended, but the link provided previously:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basic_access_authentication#Client_side

...specifies to Base64 encode "Basic username:password". We actually use this process with other API providers (all of whom are OAuth2-based), so we are familiar, but with these providers they have us Base64 encode the CLIENT_ID and CLIENT_SECRET for our specific application; for example, "Basic CLIENT_ID:CLIENT_SECRET". Cliniko, last we checked, does not utilize OAuth2 or application-specific CLIENT_IDs and CLIENT_SECRETs, which is why we designed Cliniko API access in the manner we did.

Therefore, when we create the authorization header for Cliniko, should we use the user's Cliniko email address as the username, and the user's Cliniko API key as the password? We are trying this now with known-good code and Cliniko is returning 401s. 

Thank you.

**Comment by JohnColvin** [comment]
Hi there,

You'll need to send the user's API key as the basic auth username and leave the password blank. There's no need to send the user's email address.

Hope that gets you in!

**Comment by TM818** [comment]
Switched the Authorization header to a Base64 encode of "Basic API_KEY", worked perfectly. Thank you.

**Comment by TM818** [comment]
Switched the Authorization header to a Base64 encode of "Basic API_KEY", worked perfectly. Thank you.

Quick follow-up question: In the case of multiple pages of query results, when accessing the ['links']['next'] value, do we specify the authorization header every time, or do we simply query that URL and parse the results, moving to the next page until ['links']['next'] is nil?

**Comment by JohnColvin** [comment]
:+1: Good to hear you got right in.

You need to send the authorization header on every request you send to the API. Following `[links']['next']` until there isn't one, is the correct way to read through an entire collection.

**Comment by TM818** [comment]
Worked perfectly, thank you.
