### ISSUE TITLE
Question regarding getting all records created or updated since specific date.

### ISSUE THREAD

**Issue by TM818** [redguava/cliniko-api#103]
Regarding getting all records (patients, appointments, cancelled appointments, invoices, practitioners, etc) since a given date, is it enough to simply apply a filter for all records with an updated_at value since the last time we checked? Will this work not only for updated records, but records newly-created since that date? 

Thank you.

**Comment by JohnColvin** [comment]
Yep, that will work for newly created records, as well. A new record has its `updated_at` timestamp set, as well as the `created_at` timestamp.

**Comment by TM818** [comment]
Perfect, thank you.
