### ISSUE TITLE
Cliniko Page not displaying through custom app

### ISSUE THREAD

**Issue by RichMonDons** [redguava/cliniko-api#104]
Richard Monheit
Nov 6, 7:37 AM

Hello,

I'm building an app for Hawksburn Health which includes a number of value adding tools - one of them being a direct link to your booking page.

When I open it on a web browser (apple or otherwise) on a desktop it works perfectly. 
When I open it on a web browser (apple or otherwise) on mobile/tablet it works perfectly. 
When I open through the app on an Android phone it works perfectly. 
When I open it through the app on an Apple device it says the page isn't there (attached screenshot)? The app is opened on the same device where it worked through safari.
![img_1283](https://cloud.githubusercontent.com/assets/15678632/10981909/7a9abeda-845e-11e5-9dd7-f61cfbfeea19.PNG)

Can you please investigate why this is the case? The two pages that I'm linking too are;

https://facingeast.cliniko.com/bookings#service
https://hawksburn-health.cliniko.com/bookings#service

Please advise/turn off whatever is blocking me to do so.

Thanks
Richard

**Comment by JohnColvin** [comment]
Hi Richard,

This is very odd. I'm afraid this is a new one to me. If it were a security header or the like, I wouldn't expect the 404 page. That's also the 404 from the app, which is different from online bookings.

Are you able to pull out some response info from the app? Some questions that come to mind: are you getting redirected? What headers are you sending us? What headers do we send back?

Thanks!

**Comment by RichMonDons** [comment]
Hi John,

Ill pass that on to the dev team but can you confirm thats the link I
should be using?

**Comment by JohnColvin** [comment]
You should not need `#service` on the end. Give just `https://hawksburn-health.cliniko.com/bookings` a try.

**Comment by RichMonDons** [comment]
Hi there,

That seemed to fix it - didn't like the redirect! :P

Thanks all
