### ISSUE TITLE
BUG: paging broken

### ISSUE THREAD

**Issue by nathanblogs** [redguava/cliniko-api#106]
Hello,

Paging looks broken for available_times, when I follow the next page it always returns the first page this continues onto page 3,4....x.

example:

curl -u API_KEY: -H 'Accept: application/json' 'https://api.cliniko.com/v1/businesses/8061/practitioners/11999/appointment_types/32998/available_times?from=2015-11-11&to=2015-11-16'

`
{"available_times":[{"appointment_start":"2015-11-11T01:00:00Z"},{"appointment_start":"2015-11-11T01:15:00Z"},{"appointment_start":"2015-11-11T01:30:00Z"},{"appointment_start":"2015-11-11T01:45:00Z"},{"appointment_start":"2015-11-11T02:00:00Z"},{"appointment_start":"2015-11-11T06:00:00Z"},{"appointment_start":"2015-11-11T06:15:00Z"},{"appointment_start":"2015-11-11T06:30:00Z"},{"appointment_start":"2015-11-11T06:45:00Z"},{"appointment_start":"2015-11-11T07:00:00Z"},{"appointment_start":"2015-11-11T07:15:00Z"},{"appointment_start":"2015-11-11T07:30:00Z"},{"appointment_start":"2015-11-11T07:45:00Z"},{"appointment_start":"2015-11-11T08:00:00Z"},{"appointment_start":"2015-11-11T08:15:00Z"},{"appointment_start":"2015-11-11T08:30:00Z"},{"appointment_start":"2015-11-11T08:45:00Z"},{"appointment_start":"2015-11-12T01:00:00Z"},{"appointment_start":"2015-11-12T01:15:00Z"},{"appointment_start":"2015-11-12T01:30:00Z"},{"appointment_start":"2015-11-12T01:45:00Z"},{"appointment_start":"2015-11-12T02:00:00Z"},{"appointment_start":"2015-11-12T02:15:00Z"},{"appointment_start":"2015-11-12T02:30:00Z"},{"appointment_start":"2015-11-12T02:45:00Z"},{"appointment_start":"2015-11-12T03:00:00Z"},{"appointment_start":"2015-11-12T03:15:00Z"},{"appointment_start":"2015-11-12T03:30:00Z"},{"appointment_start":"2015-11-12T03:45:00Z"},{"appointment_start":"2015-11-12T04:00:00Z"},{"appointment_start":"2015-11-12T04:15:00Z"},{"appointment_start":"2015-11-12T04:30:00Z"},{"appointment_start":"2015-11-12T04:45:00Z"},{"appointment_start":"2015-11-12T05:00:00Z"},{"appointment_start":"2015-11-12T05:15:00Z"},{"appointment_start":"2015-11-12T05:30:00Z"},{"appointment_start":"2015-11-12T05:45:00Z"},{"appointment_start":"2015-11-12T06:00:00Z"},{"appointment_start":"2015-11-12T06:15:00Z"},{"appointment_start":"2015-11-12T06:30:00Z"},{"appointment_start":"2015-11-12T06:45:00Z"},{"appointment_start":"2015-11-12T07:00:00Z"},{"appointment_start":"2015-11-12T07:15:00Z"},{"appointment_start":"2015-11-12T07:30:00Z"},{"appointment_start":"2015-11-12T07:45:00Z"},{"appointment_start":"2015-11-12T08:00:00Z"},{"appointment_start":"2015-11-12T08:15:00Z"},{"appointment_start":"2015-11-12T08:30:00Z"},{"appointment_start":"2015-11-12T08:45:00Z"},{"appointment_start":"2015-11-13T01:00:00Z"},{"appointment_start":"2015-11-13T01:15:00Z"},{"appointment_start":"2015-11-13T01:30:00Z"},{"appointment_start":"2015-11-13T01:45:00Z"},{"appointment_start":"2015-11-13T02:00:00Z"},{"appointment_start":"2015-11-13T02:15:00Z"},{"appointment_start":"2015-11-13T02:30:00Z"},{"appointment_start":"2015-11-13T02:45:00Z"},{"appointment_start":"2015-11-13T03:00:00Z"},{"appointment_start":"2015-11-13T03:15:00Z"},{"appointment_start":"2015-11-13T03:30:00Z"},{"appointment_start":"2015-11-13T03:45:00Z"},{"appointment_start":"2015-11-13T04:00:00Z"},{"appointment_start":"2015-11-13T04:15:00Z"},{"appointment_start":"2015-11-13T04:30:00Z"},{"appointment_start":"2015-11-13T04:45:00Z"},{"appointment_start":"2015-11-13T05:00:00Z"},{"appointment_start":"2015-11-13T05:15:00Z"},{"appointment_start":"2015-11-13T05:30:00Z"},{"appointment_start":"2015-11-13T05:45:00Z"},{"appointment_start":"2015-11-13T06:00:00Z"},{"appointment_start":"2015-11-13T06:15:00Z"},{"appointment_start":"2015-11-13T06:30:00Z"},{"appointment_start":"2015-11-13T06:45:00Z"},{"appointment_start":"2015-11-13T07:00:00Z"},{"appointment_start":"2015-11-13T07:15:00Z"},{"appointment_start":"2015-11-13T07:30:00Z"},{"appointment_start":"2015-11-13T07:45:00Z"},{"appointment_start":"2015-11-13T08:00:00Z"},{"appointment_start":"2015-11-13T08:15:00Z"},{"appointment_start":"2015-11-13T08:30:00Z"},{"appointment_start":"2015-11-13T08:45:00Z"},{"appointment_start":"2015-11-14T01:00:00Z"},{"appointment_start":"2015-11-14T01:15:00Z"},{"appointment_start":"2015-11-14T01:30:00Z"},{"appointment_start":"2015-11-14T01:45:00Z"},{"appointment_start":"2015-11-14T02:00:00Z"},{"appointment_start":"2015-11-14T02:15:00Z"},{"appointment_start":"2015-11-14T02:30:00Z"},{"appointment_start":"2015-11-14T02:45:00Z"},{"appointment_start":"2015-11-14T03:00:00Z"},{"appointment_start":"2015-11-14T03:15:00Z"},{"appointment_start":"2015-11-14T03:30:00Z"},{"appointment_start":"2015-11-14T03:45:00Z"},{"appointment_start":"2015-11-14T04:00:00Z"},{"appointment_start":"2015-11-14T04:15:00Z"},{"appointment_start":"2015-11-14T04:30:00Z"},{"appointment_start":"2015-11-14T04:45:00Z"},{"appointment_start":"2015-11-14T05:00:00Z"},{"appointment_start":"2015-11-14T05:15:00Z"},{"appointment_start":"2015-11-14T05:30:00Z"},{"appointment_start":"2015-11-14T05:45:00Z"},{"appointment_start":"2015-11-14T06:00:00Z"},{"appointment_start":"2015-11-14T06:15:00Z"},{"appointment_start":"2015-11-14T06:30:00Z"},{"appointment_start":"2015-11-14T06:45:00Z"},{"appointment_start":"2015-11-14T07:00:00Z"},{"appointment_start":"2015-11-14T07:15:00Z"},{"appointment_start":"2015-11-14T07:30:00Z"},{"appointment_start":"2015-11-14T07:45:00Z"},{"appointment_start":"2015-11-14T08:00:00Z"},{"appointment_start":"2015-11-14T08:15:00Z"},{"appointment_start":"2015-11-14T08:30:00Z"},{"appointment_start":"2015-11-14T08:45:00Z"},{"appointment_start":"2015-11-14T17:00:00Z"},{"appointment_start":"2015-11-14T17:15:00Z"},{"appointment_start":"2015-11-14T17:30:00Z"},{"appointment_start":"2015-11-14T17:45:00Z"},{"appointment_start":"2015-11-14T18:00:00Z"},{"appointment_start":"2015-11-14T18:15:00Z"},{"appointment_start":"2015-11-14T18:30:00Z"},{"appointment_start":"2015-11-14T18:45:00Z"},{"appointment_start":"2015-11-14T19:00:00Z"},{"appointment_start":"2015-11-14T19:15:00Z"},{"appointment_start":"2015-11-14T19:30:00Z"},{"appointment_start":"2015-11-14T19:45:00Z"},{"appointment_start":"2015-11-14T20:00:00Z"},{"appointment_start":"2015-11-14T20:15:00Z"},{"appointment_start":"2015-11-14T20:30:00Z"},{"appointment_start":"2015-11-14T20:45:00Z"},{"appointment_start":"2015-11-14T21:00:00Z"},{"appointment_start":"2015-11-14T21:15:00Z"},{"appointment_start":"2015-11-14T21:30:00Z"},{"appointment_start":"2015-11-14T21:45:00Z"},{"appointment_start":"2015-11-14T22:00:00Z"},{"appointment_start":"2015-11-14T22:15:00Z"},{"appointment_start":"2015-11-14T22:30:00Z"},{"appointment_start":"2015-11-14T22:45:00Z"},{"appointment_start":"2015-11-14T23:00:00Z"},{"appointment_start":"2015-11-14T23:15:00Z"},{"appointment_start":"2015-11-14T23:30:00Z"},{"appointment_start":"2015-11-14T23:45:00Z"},{"appointment_start":"2015-11-16T01:00:00Z"},{"appointment_start":"2015-11-16T01:15:00Z"},{"appointment_start":"2015-11-16T01:30:00Z"},{"appointment_start":"2015-11-16T01:45:00Z"},{"appointment_start":"2015-11-16T02:00:00Z"},{"appointment_start":"2015-11-16T02:15:00Z"},{"appointment_start":"2015-11-16T02:30:00Z"},{"appointment_start":"2015-11-16T02:45:00Z"},{"appointment_start":"2015-11-16T03:00:00Z"},{"appointment_start":"2015-11-16T03:15:00Z"},{"appointment_start":"2015-11-16T03:30:00Z"},{"appointment_start":"2015-11-16T03:45:00Z"},{"appointment_start":"2015-11-16T05:00:00Z"},{"appointment_start":"2015-11-16T05:15:00Z"},{"appointment_start":"2015-11-16T05:30:00Z"},{"appointment_start":"2015-11-16T05:45:00Z"},{"appointment_start":"2015-11-16T06:00:00Z"},{"appointment_start":"2015-11-16T06:15:00Z"},{"appointment_start":"2015-11-16T06:30:00Z"},{"appointment_start":"2015-11-16T06:45:00Z"},{"appointment_start":"2015-11-16T07:00:00Z"},{"appointment_start":"2015-11-16T07:15:00Z"},{"appointment_start":"2015-11-16T07:30:00Z"},{"appointment_start":"2015-11-16T07:45:00Z"},{"appointment_start":"2015-11-16T08:00:00Z"},{"appointment_start":"2015-11-16T08:15:00Z"},{"appointment_start":"2015-11-16T08:30:00Z"},{"appointment_start":"2015-11-16T08:45:00Z"}],"total_entries":169,"links":{"next":"https://api.cliniko.com/v1/businesses/8061/practitioners/11999/appointment_types/32998/available_times?from=2015-11-11&to=2015-11-16&page=2","self":"https://api.cliniko.com/v1/businesses/8061/practitioners/11999/appointment_types/32998/available_times?from=2015-11-11&to=2015-11-16&page=1"}}
`

curl -u API_KEY: -H 'Accept: application/json' 'https://api.cliniko.com/v1/businesses/8061/practitioners/11999/appointment_types/32998/available_times?from=2015-11-11&to=2015-11-16&page=2'

`
{"available_times":[{"appointment_start":"2015-11-11T01:00:00Z"},{"appointment_start":"2015-11-11T01:15:00Z"},{"appointment_start":"2015-11-11T01:30:00Z"},{"appointment_start":"2015-11-11T01:45:00Z"},{"appointment_start":"2015-11-11T02:00:00Z"},{"appointment_start":"2015-11-11T06:00:00Z"},{"appointment_start":"2015-11-11T06:15:00Z"},{"appointment_start":"2015-11-11T06:30:00Z"},{"appointment_start":"2015-11-11T06:45:00Z"},{"appointment_start":"2015-11-11T07:00:00Z"},{"appointment_start":"2015-11-11T07:15:00Z"},{"appointment_start":"2015-11-11T07:30:00Z"},{"appointment_start":"2015-11-11T07:45:00Z"},{"appointment_start":"2015-11-11T08:00:00Z"},{"appointment_start":"2015-11-11T08:15:00Z"},{"appointment_start":"2015-11-11T08:30:00Z"},{"appointment_start":"2015-11-11T08:45:00Z"},{"appointment_start":"2015-11-12T01:00:00Z"},{"appointment_start":"2015-11-12T01:15:00Z"},{"appointment_start":"2015-11-12T01:30:00Z"},{"appointment_start":"2015-11-12T01:45:00Z"},{"appointment_start":"2015-11-12T02:00:00Z"},{"appointment_start":"2015-11-12T02:15:00Z"},{"appointment_start":"2015-11-12T02:30:00Z"},{"appointment_start":"2015-11-12T02:45:00Z"},{"appointment_start":"2015-11-12T03:00:00Z"},{"appointment_start":"2015-11-12T03:15:00Z"},{"appointment_start":"2015-11-12T03:30:00Z"},{"appointment_start":"2015-11-12T03:45:00Z"},{"appointment_start":"2015-11-12T04:00:00Z"},{"appointment_start":"2015-11-12T04:15:00Z"},{"appointment_start":"2015-11-12T04:30:00Z"},{"appointment_start":"2015-11-12T04:45:00Z"},{"appointment_start":"2015-11-12T05:00:00Z"},{"appointment_start":"2015-11-12T05:15:00Z"},{"appointment_start":"2015-11-12T05:30:00Z"},{"appointment_start":"2015-11-12T05:45:00Z"},{"appointment_start":"2015-11-12T06:00:00Z"},{"appointment_start":"2015-11-12T06:15:00Z"},{"appointment_start":"2015-11-12T06:30:00Z"},{"appointment_start":"2015-11-12T06:45:00Z"},{"appointment_start":"2015-11-12T07:00:00Z"},{"appointment_start":"2015-11-12T07:15:00Z"},{"appointment_start":"2015-11-12T07:30:00Z"},{"appointment_start":"2015-11-12T07:45:00Z"},{"appointment_start":"2015-11-12T08:00:00Z"},{"appointment_start":"2015-11-12T08:15:00Z"},{"appointment_start":"2015-11-12T08:30:00Z"},{"appointment_start":"2015-11-12T08:45:00Z"},{"appointment_start":"2015-11-13T01:00:00Z"},{"appointment_start":"2015-11-13T01:15:00Z"},{"appointment_start":"2015-11-13T01:30:00Z"},{"appointment_start":"2015-11-13T01:45:00Z"},{"appointment_start":"2015-11-13T02:00:00Z"},{"appointment_start":"2015-11-13T02:15:00Z"},{"appointment_start":"2015-11-13T02:30:00Z"},{"appointment_start":"2015-11-13T02:45:00Z"},{"appointment_start":"2015-11-13T03:00:00Z"},{"appointment_start":"2015-11-13T03:15:00Z"},{"appointment_start":"2015-11-13T03:30:00Z"},{"appointment_start":"2015-11-13T03:45:00Z"},{"appointment_start":"2015-11-13T04:00:00Z"},{"appointment_start":"2015-11-13T04:15:00Z"},{"appointment_start":"2015-11-13T04:30:00Z"},{"appointment_start":"2015-11-13T04:45:00Z"},{"appointment_start":"2015-11-13T05:00:00Z"},{"appointment_start":"2015-11-13T05:15:00Z"},{"appointment_start":"2015-11-13T05:30:00Z"},{"appointment_start":"2015-11-13T05:45:00Z"},{"appointment_start":"2015-11-13T06:00:00Z"},{"appointment_start":"2015-11-13T06:15:00Z"},{"appointment_start":"2015-11-13T06:30:00Z"},{"appointment_start":"2015-11-13T06:45:00Z"},{"appointment_start":"2015-11-13T07:00:00Z"},{"appointment_start":"2015-11-13T07:15:00Z"},{"appointment_start":"2015-11-13T07:30:00Z"},{"appointment_start":"2015-11-13T07:45:00Z"},{"appointment_start":"2015-11-13T08:00:00Z"},{"appointment_start":"2015-11-13T08:15:00Z"},{"appointment_start":"2015-11-13T08:30:00Z"},{"appointment_start":"2015-11-13T08:45:00Z"},{"appointment_start":"2015-11-14T01:00:00Z"},{"appointment_start":"2015-11-14T01:15:00Z"},{"appointment_start":"2015-11-14T01:30:00Z"},{"appointment_start":"2015-11-14T01:45:00Z"},{"appointment_start":"2015-11-14T02:00:00Z"},{"appointment_start":"2015-11-14T02:15:00Z"},{"appointment_start":"2015-11-14T02:30:00Z"},{"appointment_start":"2015-11-14T02:45:00Z"},{"appointment_start":"2015-11-14T03:00:00Z"},{"appointment_start":"2015-11-14T03:15:00Z"},{"appointment_start":"2015-11-14T03:30:00Z"},{"appointment_start":"2015-11-14T03:45:00Z"},{"appointment_start":"2015-11-14T04:00:00Z"},{"appointment_start":"2015-11-14T04:15:00Z"},{"appointment_start":"2015-11-14T04:30:00Z"},{"appointment_start":"2015-11-14T04:45:00Z"},{"appointment_start":"2015-11-14T05:00:00Z"},{"appointment_start":"2015-11-14T05:15:00Z"},{"appointment_start":"2015-11-14T05:30:00Z"},{"appointment_start":"2015-11-14T05:45:00Z"},{"appointment_start":"2015-11-14T06:00:00Z"},{"appointment_start":"2015-11-14T06:15:00Z"},{"appointment_start":"2015-11-14T06:30:00Z"},{"appointment_start":"2015-11-14T06:45:00Z"},{"appointment_start":"2015-11-14T07:00:00Z"},{"appointment_start":"2015-11-14T07:15:00Z"},{"appointment_start":"2015-11-14T07:30:00Z"},{"appointment_start":"2015-11-14T07:45:00Z"},{"appointment_start":"2015-11-14T08:00:00Z"},{"appointment_start":"2015-11-14T08:15:00Z"},{"appointment_start":"2015-11-14T08:30:00Z"},{"appointment_start":"2015-11-14T08:45:00Z"},{"appointment_start":"2015-11-14T17:00:00Z"},{"appointment_start":"2015-11-14T17:15:00Z"},{"appointment_start":"2015-11-14T17:30:00Z"},{"appointment_start":"2015-11-14T17:45:00Z"},{"appointment_start":"2015-11-14T18:00:00Z"},{"appointment_start":"2015-11-14T18:15:00Z"},{"appointment_start":"2015-11-14T18:30:00Z"},{"appointment_start":"2015-11-14T18:45:00Z"},{"appointment_start":"2015-11-14T19:00:00Z"},{"appointment_start":"2015-11-14T19:15:00Z"},{"appointment_start":"2015-11-14T19:30:00Z"},{"appointment_start":"2015-11-14T19:45:00Z"},{"appointment_start":"2015-11-14T20:00:00Z"},{"appointment_start":"2015-11-14T20:15:00Z"},{"appointment_start":"2015-11-14T20:30:00Z"},{"appointment_start":"2015-11-14T20:45:00Z"},{"appointment_start":"2015-11-14T21:00:00Z"},{"appointment_start":"2015-11-14T21:15:00Z"},{"appointment_start":"2015-11-14T21:30:00Z"},{"appointment_start":"2015-11-14T21:45:00Z"},{"appointment_start":"2015-11-14T22:00:00Z"},{"appointment_start":"2015-11-14T22:15:00Z"},{"appointment_start":"2015-11-14T22:30:00Z"},{"appointment_start":"2015-11-14T22:45:00Z"},{"appointment_start":"2015-11-14T23:00:00Z"},{"appointment_start":"2015-11-14T23:15:00Z"},{"appointment_start":"2015-11-14T23:30:00Z"},{"appointment_start":"2015-11-14T23:45:00Z"},{"appointment_start":"2015-11-16T01:00:00Z"},{"appointment_start":"2015-11-16T01:15:00Z"},{"appointment_start":"2015-11-16T01:30:00Z"},{"appointment_start":"2015-11-16T01:45:00Z"},{"appointment_start":"2015-11-16T02:00:00Z"},{"appointment_start":"2015-11-16T02:15:00Z"},{"appointment_start":"2015-11-16T02:30:00Z"},{"appointment_start":"2015-11-16T02:45:00Z"},{"appointment_start":"2015-11-16T03:00:00Z"},{"appointment_start":"2015-11-16T03:15:00Z"},{"appointment_start":"2015-11-16T03:30:00Z"},{"appointment_start":"2015-11-16T03:45:00Z"},{"appointment_start":"2015-11-16T05:00:00Z"},{"appointment_start":"2015-11-16T05:15:00Z"},{"appointment_start":"2015-11-16T05:30:00Z"},{"appointment_start":"2015-11-16T05:45:00Z"},{"appointment_start":"2015-11-16T06:00:00Z"},{"appointment_start":"2015-11-16T06:15:00Z"},{"appointment_start":"2015-11-16T06:30:00Z"},{"appointment_start":"2015-11-16T06:45:00Z"},{"appointment_start":"2015-11-16T07:00:00Z"},{"appointment_start":"2015-11-16T07:15:00Z"},{"appointment_start":"2015-11-16T07:30:00Z"},{"appointment_start":"2015-11-16T07:45:00Z"},{"appointment_start":"2015-11-16T08:00:00Z"},{"appointment_start":"2015-11-16T08:15:00Z"},{"appointment_start":"2015-11-16T08:30:00Z"},{"appointment_start":"2015-11-16T08:45:00Z"}],"total_entries":169,"links":{"next":"https://api.cliniko.com/v1/businesses/8061/practitioners/11999/appointment_types/32998/available_times?from=2015-11-11&to=2015-11-16&page=3","previous":"https://api.cliniko.com/v1/businesses/8061/practitioners/11999/appointment_types/32998/available_times?from=2015-11-11&to=2015-11-16&page=1","self":"https://api.cliniko.com/v1/businesses/8061/practitioners/11999/appointment_types/32998/available_times?from=2015-11-11&to=2015-11-16&page=2"}}
`

**Comment by JohnColvin** [comment]
Hi Nathan,

Thanks for the report. It looks like this endpoint is returning the proper pagination links, but returns all of the data regardless of the pagination parameters. I believe it has always inadvertently done this, but I'm checking with the rest of the team to be sure. If that's the case, we will probably continue serving the data as is (to not break things for apps expecting the current buggy behavior), add a disclaimer in the docs here, and put on our list of things to fix in v2.

I'll let you know what we decide. Thanks again!

**Comment by hagen** [comment]
Closing due to age. Please reopen if required.
