### ISSUE TITLE
Users API returns 403

### ISSUE THREAD

**Issue by luizfelipepg** [redguava/cliniko-api#112]
Hi all, 

We are calling the practitioners API to get all practitioners but when we call the user link inside the practitioner, we are getting 403. We are calling the user API to get the timezone and email for a specific practitioner.

Thanks for your help.
Cheers,
Luiz

**Comment by luizfelipepg** [comment]
By the way, this is happening only for one specific practice so far

**Comment by bpinto** [comment]
If you are getting a Forbidden (403 response code) back, that means your API token does not have permission to see that user information. Unless that token is for an admin, you cannot read other user information.

Or are you trying to read your own user information?

**Comment by luizfelipepg** [comment]
Ahh, so you are saying the API Key has to be generated by the administrator ?

**Comment by bpinto** [comment]
Yes, user permissions using the API are the same as when not using the API, we have a [permission matrix](https://support.cliniko.com/hc/en-us/articles/204618260-Security-Role-Permissions-Matrix) that explains it.

**Comment by luizfelipepg** [comment]
In the case of the User Information, the scheduler can not add/edit other users information, what about view ???

In our case we are using a scheduler account but we just want to view users information.

**Comment by bpinto** [comment]
Oh sorry about that, we are going to add the missing "View" to the row name. Only administrators can read other user information.

**Comment by luizfelipepg** [comment]
Ahhh ok, got it :)

Thanks :+1:

**Comment by bpinto** [comment]
:+1:

**Comment by luizfelipepg** [comment]
I might be asking too much but any reason why I can not get timezone and e-mail as part of the practitioner API ? I am only calling the user API to get this two fields.

Not a big deal but it would save me an API call and the need of an administrator account to complete the synchronization.

**Comment by bpinto** [comment]
To be honest, we shouldn't have the user first name and last name available on the practitioner resource as that is an information users that are not administrators shouldn't have access to.

**Comment by bpinto** [comment]
I have updated the security matrix.

**Comment by luizfelipepg** [comment]
thanks :+1:

**Comment by chiragtechuz** [comment]
how to set permission a particuarl api for particualr route
