### ISSUE TITLE
Question regarding determining the product or service associated to a Cliniko invoice.

### ISSUE THREAD

**Issue by TM818** [redguava/cliniko-api#113]
We have a customer very interested in our ability to determine the Cliniko product (or service, not sure if that's a separate table) associated with a given Cliniko invoice. Per the current documentation, it appears that a Cliniko invoice returned over the API displays the associated appointment, business, practitioner, and patient, but not product (or service). Is there a way to determine the associated product or service?

**Comment by jfriedlaender** [comment]
You can get this information from the invoice items endpoint:
https://github.com/redguava/cliniko-api/blob/master/sections/invoice_items.md
