### ISSUE TITLE
Question regarding invoice_item table IDs.

### ISSUE THREAD

**Issue by TM818** [redguava/cliniko-api#114]
Am I correct in noticing that Cliniko creates a new table ID for each invoice_item applied to an invoice, even if it's the same invoice_item used on other invoices? For example, say we have an invoice_item named "Initial Consultation", and we apply that same invoice_item to three separate invoices. Does Cliniko really create a unique table ID every time this same invoice_item is applied to a new invoice? If not, I apologize, but if so, what is the logic behind this decision? Thank you.

**Comment by jfriedlaender** [comment]
Hi,

So we have a concept called a billable item, that's basically the list of services that are provided.  I think this is what you are thinking about.  We don't have them on the API yet though.

Invoice items, are the line items of an actual invoice (internally, they link to a billable item).

Does that make sense?

Joel

**Comment by TM818** [comment]
It does, sure. We're adding a specific piece of functionality to our application based on these invoice items (the services rendered on invoices). As the table ID of these invoice_items changes from invoice to invoice, I suppose storing by the name of the invoice item (instead of the table ID as we usually do) would be sufficient, yes?

**Comment by jfriedlaender** [comment]
It would be your best way right now, but they can change the name and it would mess with things for you.  It's your best option right now, but I'll see if we can get billable items added soon.  Keep an eye on the google group!

**Comment by TM818** [comment]
Will do, thank you.

**Comment by TM818** [comment]
Out of curiosity, what would the timetable be for making the billable items available via the API?

**Comment by bpinto** [comment]
We are focusing on calendar (appointments, patients, etc.) entry points at the moment as we have a big feature coming soon, after this we will probably focus on the invoice page and use the API ourselves so we would focus on the API for these. That would still be a few months away though. =/

**Comment by TM818** [comment]
Oh man, that's a shame. It looks like using even the invoice_item name itself isn't possible, since a unique entry is generated on every single invoice, the amount of data returned when pulling this data is large, to the point that it is unusable. We told users we'd have this feature available for them, since when we asked Cliniko's API team previously, they told us we could access such data via the invoice item table, but obviously that's not the case. 

As we have a fairly high profile app linking Cliniko to a popular global CRM solution, is there any chance we can get this request moved up the priority chain?

**Comment by TM818** [comment]
Regarding this, assuming it behaves as the rest of the Cliniko API infrastructure, we don't need documentation, just API access to that table.

**Comment by jfriedlaender** [comment]
Can you email me with the details of what you are doing?

**Comment by TM818** [comment]
Sure, what's the best email address to reach you?

**Comment by TM818** [comment]
Disregard, I have your address.

**Comment by TM818** [comment]
This issue can be closed.
