### ISSUE TITLE
Suddenly receiving 403 Forbidden responses from Cliniko API endpoint. 

### ISSUE THREAD

**Issue by TM818** [redguava/cliniko-api#116]
Quick question: We're suddenly receiving 403 forbidden responses from the Cliniko API for a specific user. This has been happening for the past 10 minutes. Nothing has changed in our app, is this expected? It's currently 12/23/2015 23:29 UTC. Checking to see if this is a user-specific issue or a known global outage. We can provide further user-specific detail if needed. Thank you.

**Comment by TM818** [comment]
This issue appears resolved.

**Comment by bpinto** [comment]
Hey @TM818

Could you send me an email bruno @ cliniko.com with further information? Id like to have a closer look.
