### ISSUE TITLE
Question regarding pulling company subdomain from API.

### ISSUE THREAD

**Issue by TM818** [redguava/cliniko-api#123]
Is it possible to return a given company's Cliniko subdomain via the API? For example, if the company is xyzcompany.cliniko.com, is there an API method for returning the "xyzcompany" part, or at least their full proper Cilniko URL so the company subdomain can be extracted?

**Comment by jfriedlaender** [comment]
We've just added this with #124.

You can see the docs for it here https://github.com/redguava/cliniko-api/blob/master/sections/settings.md

**Comment by TM818** [comment]
Awesome Joel, thank you.
