### ISSUE TITLE
Get Practitioners no longer returning "default_appointment_type"

### ISSUE THREAD

**Issue by RyanPaddy** [redguava/cliniko-api#128]
Our site has started throwing errors because "default_appointment_type" is no longer being returned for each practitioner when we call Get Practitioners.

**Comment by bpinto** [comment]
Hi @RyanPaddy, sorry to hear you are having problems.

A practitioner does not need to have a default appointment type set. If one does not have it set, the JSON response will simply not have this key. If however, the practitioner does have a default appointment type set, this key will be present.

You need to handle both scenarios.
