### ISSUE TITLE
Accessing most_recent_business_visited for a patient. 

### ISSUE THREAD

**Issue by TM818** [redguava/cliniko-api#130]
Question - is it possible to determine which business a patient most recently visited via the API (patient.most_recent_business_visited)? Any way to determine this would be fine. Thank you in advance for any help.

**Comment by JohnColvin** [comment]
You can query for the most recent appointment for a patient, which will give you a link to the business.

Something like this should do it for you: `api.cliniko.com/v1/appointments?q=patient_id:=621&sort=appointment_start&order=desc&per_page=1`

**Comment by bpinto** [comment]
You may also want to filter by appointments that happened before now or another time.

`api.cliniko.com/v1/patients/296/appointments?q=appointment_start:<2016-08-29T17:31:43.113Z&sort=appointment_start&order=desc&per_page=1`
