### ISSUE TITLE
Include related billable items in appointment types API response

### ISSUE THREAD

**Issue by richardlay** [redguava/cliniko-api#131]
When managing an appointment type on the Cliniko web app, you can specify a related billable item. However the appointment type APIs don't include the related billable item in the response.

**Comment by JohnColvin** [comment]
We'll be adding this soon. We'll let you know once we've deployed the change. Thanks for the request!

**Comment by JohnColvin** [comment]
I've just merged this change. It'll be deployed to production very soon. We added a link to the related product, as well.

**Comment by richardlay** [comment]
Thanks
