### ISSUE TITLE
Insert appointment type without 'show_in_online_bookings'

### ISSUE THREAD

**Issue by jradtilbrook** [redguava/cliniko-api#133]
First off, sorry if this is a duplicate, I had a look through the issues and couldn't find a similar one.

When I query for availability with an appointment type that is disabled for online bookings, I receive a 404. However, I am able to insert an appointment with that type. Is this intentional?

**Comment by bpinto** [comment]
I think you are using the [available times](https://github.com/redguava/cliniko-api/blob/master/sections/available_times.md) end point.

That end point is for online bookings only and in case the business, practitioner or appointment type is not enabled for online bookings it will return a 404.

If you need to see all appointments I recommend you having a look at the [Appointments](https://github.com/redguava/cliniko-api/blob/master/sections/appointments.md) end point.

**Comment by jradtilbrook** [comment]
Yes I was referring to the available times end point. For my application, I need to retrieve the available times for a business/practitioner combination. The way I see it currently, I must use a business/practitioner/appointment_type combination to retrieve the available appointment starting times for each type. Can you confirm this?

The issue I was referring to here is that I am able to create an appointment with an appointment type that is disabled for online bookings. Is that intentional? Or if an appointment type is not enabled, I should also not be able to create an appointment of that type using the API.

**Comment by bpinto** [comment]
Yeah, you will have to use a combination like that. The appointment end point can be filtered using those three objects, so you could something like this:

`https://api.cliniko.com/v1/appointments?q[]=business_id:=1&q[]=appointment_type_id:=15&q[]=practition
                                                               er_id:=10'`

Regarding the creation of the appointment, by using the Cliniko API you are creating data as if you were using Cliniko Web interface, so you should be able to create the same appointments you are able to when logged in to your Cliniko account. You would not be able to create an appointment with an appointment type that is disabled for online bookings only on the Clinic's online bookings page.

**Comment by jradtilbrook** [comment]
Okay thanks for you quick replies today. 

One last thing, referring to #4 and #13, would it be possible to also expose a practitioners availability as set up in the Users & Practitioners settings page? This was raised in those issues, but a different approach was decided.

**Comment by bpinto** [comment]
We are already working on an end point for this practitioners availability you are referring to. It currently only exposes the information and does not allow you to modify it.

It should become available soon.

**Comment by jradtilbrook** [comment]
That's great, I could really use that functionality. Thank you for all your help. I'll leave you to close this issue if you're happy to.
