### ISSUE TITLE
Unable to sort practitioners

### ISSUE THREAD

**Issue by richardlay** [redguava/cliniko-api#134]
Trying to sort any of the practitioner endpoints results in a "Sort parameter must be a valid column name" response.

E.g.
`curl https://api.cliniko.com/v1/appointment_types/122381/practitioners?sort=last_name,first_name ...`

This works for the users endpoint.

**Comment by bpinto** [comment]
Confirmed this is an issue. I will get back when we have a fix for it.

**Comment by bpinto** [comment]
@richardlay this has been fixed. Thanks for raising it.
