### ISSUE TITLE
Available times for non-default appointment type

### ISSUE THREAD

**Issue by jradtilbrook** [redguava/cliniko-api#137]
There seems to be a bug in the API introduced only recently. The available times endpoint seems to only give available times based on the default appointment type set for the practitioner, rather than the appointment type supplied in the URL. Can you confirm?

**Comment by JohnColvin** [comment]
Hi Jarryd,

I don't think we've made any changes recently that would affect available times. This endpoint was originally created to power the online booking system and it's doing some under the hood magic.

We've always used the default appointment type to determine the size of the time slots. This is an assumption we make that most appointments will be of the default type. Organizing appointment slots based on the default leaves the best chance that a practitioner will not end up with unwanted gaps in their day. The endpoint uses the appointment type that you provide to decide where that type of appointment could fit in the practitioner's schedule.

There was a similar question from the google group a while back that has some more details and a concrete example: https://groups.google.com/a/redguava.com.au/forum/#!searchin/cliniko-api/available$20times%7Csort:relevance/cliniko-api/voDatAopca4/04Hh-u5_CQAJ

Let me know if that clears it up!

Cheers,
John

**Comment by jradtilbrook** [comment]
Hi John,

Thanks for letting me know - I could have sworn I was able to retrieve available slots based on the duration of the provided appointment type but must have gotten confused with all the testing/exploration I was doing.

I'll close this issue since there is no actionable item.

Thanks again,
Jarryd
