### ISSUE TITLE
GET appointments confusion for single and group appointments

### ISSUE THREAD

**Issue by jonnyfiasco** [redguava/cliniko-api#139]
Hi
I'm having trouble getting group appointments on GET /appointments.  On top of that, it is not returning deleted or cancelled appointments either.  I am having to do separate queries for these.

I have two appointments, one individual, one group.

I am attempting to GET all appointments, however only one is being returned (the individual appointment).  Can't seem to get group appointments at all.

 Can you please clarify the expected response back?

**Comment by bpinto** [comment]
We have not exposed group appointments via the API yet. The API has been published before we had support for group appointments and a new entry point will be necessary for dealing with group appointments.

Regarding cancelled or deleted appointments, they are only returned on their specific end point, so you will need to do the separate queries as you are already doing to see them.

We are discussing internally how to expose group bookings yet.

**Comment by jonnyfiasco** [comment]
Ah, thanks for the quick update - do you have any timelines on that?

**Comment by jonnyfiasco** [comment]
Also how does this issue relate to this? https://github.com/redguava/cliniko-api/issues/136

**Comment by bpinto** [comment]
We are already using a group appointment API internally we are just planning some small changes before we make it public and supported for long term. I don't have a date to share but we are discussing the changes already, we are not working on the changes yet though.

The individual appointment resource representation has a few fields that are per patient (sms reminder sent, invoice status, arrived status, notes, etc.). These fields has to migrate to a separate end point on group bookings, this new end point is called attendees.

An appointment has many attendees and each attendee is a one to one reference to a patient.
