### ISSUE TITLE
403 forbidden response on live site

### ISSUE THREAD

**Issue by squareblok** [redguava/cliniko-api#143]
Hi, I have no trouble connecting to the Cliniko api locally but when I use the same code on my live site, I'm getting a 403 Forbidden response on Patient requests. Strangely requests for Appointments don't get this error.

Any idea what the issue could be?

**Comment by JohnColvin** [comment]
That's strange! There isn't a security role that would give you access to appointments, but not patients. Is this happening with the same API key? I'd double check the security role of the user associated with the api key anyway, though.

Is it both patients index `/v1/patients` and patients details `v1/patients/:id` that give you a 403?

**Comment by squareblok** [comment]
I've managed to fix this. The site was referencing a cached file with an old api. My mistake!

Thanks for your help
