### ISSUE TITLE
Patient documentation has errors

### ISSUE THREAD

**Issue by JRosanowski** [redguava/cliniko-api#146]
https://github.com/redguava/cliniko-api/blob/master/sections/patients.md

- Typo, documentation mentions "total_entires" rather than "total_entries".
- For each patient a "label" field is returned but it's not listed in the json for a patient in the documentation.

Regards.

**Comment by bpinto** [comment]
Thanks @JRosanowski we will fix it asap!

**Comment by bpinto** [comment]
Thanks @JRosanowski we will fix it asap!

**Comment by akanshmurthy** [comment]
Can this be closed since the issue was addressed?
