### ISSUE TITLE
Can't filter patients by archived_at or deleted_at

### ISSUE THREAD

**Issue by JRosanowski** [redguava/cliniko-api#148]
Is there any intention to add filtering of patients by archived_at or deleted_at?
This wouldn't be necessary if filtering by updated_at returned patients that had been archived or deleted but it doesn't seem to do that. 

Thanks.

**Comment by JohnColvin** [comment]
It's pretty easy for us to enable filtering by those fields. I can run it by the rest of the team, but I don't see a reason why we wouldn't support filtering those.

When you're attempting to filter by `updated_at` are you hitting the `/patients/archived` or `/patients/deleted` endpoint? The `/patients` endpoint will not return archived or deleted patients.

**Comment by JRosanowski** [comment]
Whoops, my bad. I wasn't using those endpoints. Thanks.
