### ISSUE TITLE
How to create a patient and add a phone number?

### ISSUE THREAD

**Issue by richardlay** [redguava/cliniko-api#151]
I tried to include patient_phone_numbers in the payload when creating a patient, however I get a 500 internal server error.

```
...
patient_phone_numbers: [
    {
        phone_type: "Mobile",
        number: "0400000000"
    }
]
...
```

**Comment by bpinto** [comment]
Hey @richardlay 

are you sending this information encoded as json?

**Comment by richardlay** [comment]
I believe so. It works fine without `patient_phone_numbers`.

**Comment by bpinto** [comment]
Could you confirm this? I see error logs where the content type set is `application/x-www-form-urlencoded` which does not work with `patient_phone_numbers`.

If you need to reach me for more details, please send an e-mail to `support@cliniko.com` and mention my name so the e-mail is redirected to me.

**Comment by richardlay** [comment]
Sorry for late reply. Yep you were right it was an issue with the content type! Thanks.

**Comment by bpinto** [comment]
Glad it's working now. 👍
