### ISSUE TITLE
Create Attendee not working due to validation issue

### ISSUE THREAD

**Issue by lancelui** [redguava/cliniko-api#152]
Hello,

I am trying to creating a new attendee for a group appointment via the create attendee endpoint but there seems to have some validation bug.
https://github.com/redguava/cliniko-api/blob/master/sections/attendees.md#create-attendee

Running POST /v1/attendees with an appointment_id and a patient_id returns the following

```
{
  "message": "Validation Failed",
  "errors": {
    "appointment_id": "can’t be blank"
  }
}
```
The response states that appointment_id failed validation because it is blank even though an appointment_id was provided.

I have tried submitting POST v1/attendees without any data and got the following response.
```
{
  "message": "Validation Failed",
  "errors": {
    "appointment_id": "can’t be blank",
    "patient_id": "can’t be blank"
  }
}
```
This is correct and expected. So it seems like patient_id is correctly validated and the issue only lies with appointment_id.

I have tried submitting using an group appointment id and an individual appointment id and in both cases they returned appointment_id cant be blank.

**Comment by bpinto** [comment]
@lancelui 

I noticed the documentation is outdated, the parameter name is `booking_id` and not `appointment_id`. Could you retry the request with this other parameter? Thanks.

P.S.: I have updated the documentation.

**Comment by lancelui** [comment]
@bpinto 

Yes that worked. I have tried and have successfully added an attendee to a group appointment using `booking_id` as the group appointment's id parameter name.
