### ISSUE TITLE
Search on cancellation_date and when datetime is not null

### ISSUE THREAD

**Issue by evorgevol** [redguava/cliniko-api#163]
I'm trying to search on cancellation_date but getting a 400 response with the message 'This column is not searchable'. Will this be searchable in future builds? Also, if when searching for a date/datetime that is potentially nullable how do you query for null or not null?

Cheers,

evorgevol

**Comment by JohnColvin** [comment]
I'm not sure why we haven't included that as a filterable field. It's certainly something that we can do. The datetime filter does not support filtering by null or not null, though.

What endpoint are you hitting? Both the appointments and individual_appointments endpoints have a cancelled endpoint that returns only cancelled records. The normal index route does not return cancelled records. If you're just looking to filter for it being set or not, using those two endpoints should get you what you need.

**Comment by evorgevol** [comment]
Thanks for your prompt reply, I completely missed the /cancelled endpoint and can do what I needed to do with that. Thanks again, evorgevol
