### ISSUE TITLE
Ability to create invoice, and add a payment against it.

### ISSUE THREAD

**Issue by KoanLeeroy** [redguava/cliniko-api#172]
I want to invite patients, post booking (prob via email, since there's limited other ways with Cliniko) to pay for their appointment. 

Need to write something so payment can be taken after booking appointment (happy to do that), but need to record that as a credit against patient at the very least.

Perhaps via the ability to create an invoice, and add payment to it? Thus putting the patient in credit and negating the need to take payment on premises.

**Comment by bpinto** [comment]
We are starting to work on some needed backend changes before we can expose a payment API and we'll have credits in mind while working on it.

For simpler tracking, I'll be closing this issue since this is a similar request to #90

**Comment by fcbaconguis** [comment]
Hi, any updates here?

**Comment by bpinto** [comment]
@fcbaconguis nothing yet, it's unlikely it will happen this year, we are probably looking at a 2020 release.
