### ISSUE TITLE
Available times 404

### ISSUE THREAD

**Issue by richardlay** [redguava/cliniko-api#173]
Hi there,

We're trying to query the available times for one of our clients. Here is the URL we're using.

https://api.cliniko.com/v1/businesses/18047/practitioners/26224/appointment_types/72495/available_times
from=2017-07-14
to=2017-07-21

From what I can see the business, practitioner and appointment type are all enabled for online booking. Is something missing? This works fine for our other clients.

**Comment by JohnColvin** [comment]
Hi Richard,

I think the issue is the date range is too large. Do you see this error? `Invalid time frame definition. Please check from/to param limitations.` The date range has to be 6 days or less.

Cheers,
John

**Comment by richardlay** [comment]
Hi John,

Hmm no I don't see that error... I just tried with a 4 day range and I get the same response which is:
`{"status":"404","error":"Not Found"}`

This seems to be happening only for this particular account.

**Comment by JohnColvin** [comment]
I've checked those IDs and everything looks okay to me. Would you double check that you're using the right API key for that account?

**Comment by richardlay** [comment]
Yep the API key is fine.
Every other API I've called seems to be OK.
However https://api.cliniko.com/v1/available_times is the only one giving me a 404

**Comment by richardlay** [comment]
Here is my curl command:
```
curl https://api.cliniko.com/v1/businesses/18047/practitioners/26224/appointment_types/72495/available_times -u <apiKey>: -H "Accept: application/json" -H "User-Agent: Medipass" -d "from=2017-07-20" -d "to=2017-07-25"

{"status":"404","error":"Not Found"}
```

**Comment by bpinto** [comment]
@richardlay if you are using this command as is, you are sending a POST request instead of a GET request which would return a 404 since this route doesn't exist for that http verb. Is it possible you are doing the same on your original code?

**Comment by richardlay** [comment]
@bpinto thanks for that! We are using GET correctly in the code but my invalid curl test has sent me down the rabbit hole.

Turns out that we stored the wrong practitioner ID, so the issue was on our side. Thanks for your help.
