### ISSUE TITLE
Update patient not working for me

### ISSUE THREAD

**Issue by gwmathis** [redguava/cliniko-api#174]
curl https://api.cliniko.com/v1/patients/43860849 -u <My Key>: -d '{"invoice_extra_information":"****HELLO WORLD****"}' -X PUT

**Comment by bpinto** [comment]
What is the response status and message?

**Comment by gwmathis** [comment]
gmathis@ubuntu:~$ curl https://api.cliniko.com/v1/patients/43860849 -u
b1390d6b4c919024345372ad57c92f15: -d '{"invoice_extra_information":"HELLO
WORLD"}' -X PUT
{"id":43860849,"created_at":"2017-08-07T05:43:10Z","updated_at":"2017-08-07T05:47:35Z","address_1":"123
East 300
South","address_2":"","address_3":"","archived_at":null,"city":"Provo","country":"United
States","date_of_birth":"1961-03-04","deleted_at":null,"email":"
sfields@test.com","emergency_contact":"","first_name":"Sally","invoice_default_to":"","invoice_email":null,"invoice_extra_information":"Claim
#
1000","last_name":"Fields","notes":"","occupation":"","old_reference_id":"","patient_phone_numbers":[{"number":"8013334444","phone_type":"Home"},{"number":"8012223333","phone_type":"Mobile"}],"post_code":"84606","referral_source":null,"reminder_type":"SMS
& Email","state":"UT","title":"","label":"Sally
Fields","gender":"","medical_alerts":{"links":{"self":"
https://api.cliniko.com/v1/patients/43860849/medical_alerts
"}},"invoices":{"links":{"self":"
https://api.cliniko.com/v1/patients/43860849/invoices
"}},"appointments":{"links":{"self":"
https://api.cliniko.com/v1/patients/43860849/appointments
"}},"links":{"self":"https://api.cliniko.com/v1/patients/43860849"}}

gmathis@ubuntu:~$

**Comment by gwmathis** [comment]
I am not getting any errors.  It is just not updating the
invoice_extra_information
field.  Do I need to escape the JSON string?

**Comment by gwmathis** [comment]
Is it possible to update an invoice using the Cliniko API?

**Comment by bpinto** [comment]
@gwmathis have you read the link I sent to you? You are still not sending the accept or the user-agent header.

I recommend you spending 5 minutes to read the documentation and I'm sure you won't have any other question.

**Comment by gwmathis** [comment]
The Patient update is working now.  Thank you!  

Is it possible to update an Invoice using the Cliniko API?  According the documentation I don't think it is.

**Comment by sas1ni69** [comment]
Glad to hear 🎉 No, it's not possible to update invoices.
