### ISSUE TITLE
Fetching the logo image

### ISSUE THREAD

**Issue by chetem** [redguava/cliniko-api#176]
How can I fetch and download the logo image through the API?

I've tried making a `GET` request to the Settings endpoint and then grabbing the `logo_url` property, which returned what looks like another endpoint (`https://api.cliniko.com/v1/settings/online_bookings_logo`). How can I get the actual logo image using this url? It seems like I'm missing something here.

**Comment by bpinto** [comment]
Hey @chetem , when you send a GET request to this URL the response will be either a 303 with the location header set to the actual logo url or the response will be a 404 in case there is no logo.

**Comment by chetem** [comment]
Thanks @bpinto, I managed to get it going 👍
