### ISSUE TITLE
Requires a user agent

### ISSUE THREAD

**Issue by Gardezi1** [redguava/cliniko-api#177]
Hello, guys, I'm trying to connect to retrieve some contacts using your API but I keep getting the error 

```
Requires a user agent
```

Can somebody tell me what is it that I'm doing wrong

```
  public function curl_request($url, $accessToken, $param, $header="1"){

        $headers = [
            'Accept' => 'application/json',
            'User-Agent' => 'agency-mates (rohan@agencymates.com)'
        ];

        $wwwhandle = curl_init();

        curl_setopt($wwwhandle, CURLOPT_URL,'https://api.cliniko.com/v1/contacts');
        curl_setopt($wwwhandle, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($wwwhandle, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($wwwhandle, CURLOPT_USERPWD, $accessToken.":");
        if($param != "" ){
            curl_setopt($wwwhandle, CURLOPT_POST, 1);
            curl_setopt($wwwhandle, CURLOPT_POSTFIELDS, $param);
        }
        if($header == "1"){
            curl_setopt($wwwhandle, CURLOPT_HTTPHEADER, $headers);
        }

        $data = curl_exec($wwwhandle);
        
        return $data;
    }

```

Can somebody tell me what is it that is going wrong.

**Comment by Bira** [comment]
I'm not a PHP expert, but from that I read in the libcurl documentation you need to set the user agent with something like `curl_setopt($wwwhandle, CURLOPT_USERAGENT, 'agency-mates (rohan@agencymates.com)');`. CURLOPT_HTTPHEADER controls whether curl will display the headers of the response.

**Comment by Gardezi1** [comment]
@Bira oh I though I was passing it like this too. My bad. Thanks for all the help :)
