### ISSUE TITLE
Online booking settings for appointments made via API

### ISSUE THREAD

**Issue by richardlay** [redguava/cliniko-api#180]
Hi there,

I have 2 questions:

1. One of our users says they are usually alerted via a SMS/email when a booking is made via Cliniko. However for a booking that was made via the API they didn’t get the alert and accordingly wasn't there for the appointment. The appointment did populate in the calendar however. Is there a way to ensure appointments made via API trigger alerts in the same way Cliniko does?
 
2. Our user has a rule within Cliniko that a patient can't book within 4 hours of the current time. Is this setting also applied on the Get Availability API?

Thanks

**Comment by bpinto** [comment]
Hi @richardlay 

> One of our users says they are usually alerted via a SMS/email when a booking is made via Cliniko. However for a booking that was made via the API they didn’t get the alert and accordingly wasn't there for the appointment. The appointment did populate in the calendar however. Is there a way to ensure appointments made via API trigger alerts in the same way Cliniko does?

Appointments created via API or not should trigger alerts in the same way, there are some conditions for the notification to be sent however and perhaps they haven't been met. Could you ask this user to contact our support regarding this?

> Our user has a rule within Cliniko that a patient can't book within 4 hours of the current time. Is this setting also applied on the Get Availability API?

Yes, if you are using the [Available Times](https://github.com/redguava/cliniko-api/blob/master/sections/available_times.md) end point that rule will be used to give you the practitioner's available time. We don't enforce that rule when you create an appointment however.

**Comment by richardlay** [comment]
Thanks will do
