### ISSUE TITLE
Availability not returning slots that practitioner expects

### ISSUE THREAD

**Issue by richardlay** [redguava/cliniko-api#183]
Hi,

We're running an availability check via the API using:
https://api.cliniko.com/v1/businesses/53479/practitioners/80454/appointment_types/231022/available_times?from=2017-10-09&to=2017-10-15

It currently returns one result:
```
{
    "available_times": [
        {
            "appointment_start": "2017-10-13T07:00:00Z"
        }
    ],
    "links": {
        "self": "https://api.cliniko.com/v1/businesses/53479/practitioners/80454/appointment_types/231022/available_times?from=2017-10-09&to=2017-10-15&page=1"
    },
    "total_entries": 1
}
```

Which is a slot on Friday 6pm (AEDT +11). In fact, no matter which week we query for, it always returns 1 slot for the Friday at 6pm.

However, the user has shown us this screenshot with the availability for this practitioner set to

![image](https://user-images.githubusercontent.com/7135162/31323624-25a8a01e-acf6-11e7-94e7-8d235613aed2.png)

Has the user missed something in their settings?

**Comment by JohnColvin** [comment]
Hi Richard,

This is odd. I confirmed the issue, but I don't immediately see why it's happening. I'm gonna get some help from my co-worker who wrote most of that code and see what they come up with.

**Comment by bart3k** [comment]
Hi Richard, 

based on the appointment type id you used in the query it seems you are searching for a time slots in group appointment. For group bookings (as they are special type of bookings) an appointment must be created first and online bookings offers you only a space in those.

I believe this is the reason why it does not give you the results you would expect to get searching for a regular appointment.

**Comment by richardlay** [comment]
@bart3k Thanks. Yes it is a group booking. 

So I won't be able to get the correct availability for group bookings using the API?

Is this a limitation I should just inform the user about? Or is there a work around that you know of?

**Comment by bart3k** [comment]
@richardlay I believe what you received is a correct time slot for this group booking. 

Group bookings are a bit different than individual appointments and we do not allow people to create a group appointment using online bookings for a practitioner (if that is what you expected to achieve). That could lead people to have multiple group sessions with only one attendee instead of full groups where sometimes group appointments require some special arrangements to be made by a practitioner before the session (like to book a room etc.) 

In case of group bookings using this entry point we allow you to find group appointment within selected time which someone can join. 

I hope that makes sense?

I do not know what you are working on so it is hard for me to suggest any work arounds here.

**Comment by JohnColvin** [comment]
A good example is a yoga studio. They would have regularly scheduled yoga sessions that people can join through online bookings. They wouldn't want someone to be able to create a new session through online bookings.

**Comment by richardlay** [comment]
The cliniko user has said:
"It looks fine but the bookings on the app only show a time at 6pm Fridays (which are the only times we don’t have gym classes on. Have you had issues with group classes as I know the Cliniq Apps guys also have had trouble with them too. Not a big issue but would be very useful."

So it seems to be confusing him. What I need the answer to is:
How do I get the availability for regularly scheduled group sessions which I can make an appointment for via the Cliniko API?

**Comment by JohnColvin** [comment]
I recommend you query for group appointments directly with this endpoint: https://github.com/redguava/cliniko-api/blob/master/sections/group_appointments.md

You can filter on `starts_at` to get only the time range you want. If you want to be sure there's space in the appointment, you can compare the size of the `patient_ids` array with the `max_attendees` value. That's what we do on the Cliniko calendar.

Hope that helps!

**Comment by richardlay** [comment]
@JohnColvin Great, I'll take a look at that!

**Comment by richardlay** [comment]
I see a `max_attendees` field on the Get Appointment Type response. Looks like if this field is greater than 1 I can assume that there may be Group Appointments available for that appointment type? Then I would have to use the Group Appointment APIs to look up and also create the appointment. Am I correct?

**Comment by JohnColvin** [comment]
You're right on. `max_attendees` on appointment type is how we determine a group appointment. And you should use the group appointments endpoints to create or update the appointment. To add someone to a group appointment, you'll need to create an attendee record for them for the group appointment: https://github.com/redguava/cliniko-api/blob/master/sections/attendees.md

You shouldn't use the regular appointments endpoint for group appointments. The `/appointments` endpoint is essentially a legacy endpoint now. We recommend using the split endpoints:
https://github.com/redguava/cliniko-api/blob/master/sections/individual_appointments.md
https://github.com/redguava/cliniko-api/blob/master/sections/group_appointments.md
https://github.com/redguava/cliniko-api/blob/master/sections/unavailable_blocks.md
