### ISSUE TITLE
Use of PATCH method inconsistent

### ISSUE THREAD

**Issue by hagen** [redguava/cliniko-api#187]
`PATCH` HTTP verb is only used for cancelling individual appointments.
In this capacity, it appears as though it's really a _state_ modifier (i.e. from active to cancelled). No data changes, other than a date/time flag indicating cancellation of the appointment (at least from the API's perspective)
Patients can be archived, which seems also to be a state modifier. No data changes other than populating the archived_at date/time field.
Would it not make sense to also use PATCH for patient archiving/unarchiving?

**Comment by JohnColvin** [comment]
I looked back at the commit that introduced those endpoints, this was the reasoning:

> As this is not an idempotent action (has a different response when called multiple times) we are using POST.

**Comment by hagen** [comment]
That's some technical commit history right there!
Closes #187.

**Comment by JohnColvin** [comment]
Yup. All thanks to @bpinto for a detailed commit message!

**Comment by hagen** [comment]
His attention to detail is *idempotent*.
Maybe?!?!
