### ISSUE TITLE
Any filter fields for treatment note templates?

### ISSUE THREAD

**Issue by hagen** [redguava/cliniko-api#189]
Just checking if this has been accidentally omitted, or if there are no filterable fields for treatment note templates.

**Comment by JohnColvin** [comment]
Most resources (except some non-conforming ones) have filters for `id`, `created_at`, and `updated_at`. Treatment note templates have those, I just neglected to add that section.

Do you have a possible use for another filter?

**Comment by hagen** [comment]
Nope, I'm just working on something that needs to know filterable fields. The three default are fine. For meow.
Addressed with PR #191
