### ISSUE TITLE
Filter on /contacts for 'type'

### ISSUE THREAD

**Issue by hagen** [redguava/cliniko-api#193]
Request to add a filter on /contacts for field ```type``` - this will allow filtering on the type of Contact, for instances where a specific Contact type is required.

**Comment by JohnColvin** [comment]
Hey Hagen,

This is coming. It wasn't quite as easy as flipping it on because type is actually an enumeration. We're going to add the integer value as a new attribute that you'll be able to filter.

**Comment by hagen** [comment]
Brilliant, thanks gents.
