### ISSUE TITLE
created_by (user_id) field in all endpoints

### ISSUE THREAD

**Issue by hagen** [redguava/cliniko-api#197]
Hi there,

is it possible to add a created_by/user_id field in all relevant endpoints? Appointment listings for a patient in the UI show log information. This would be very useful to have in the API response too, for every endpoint where you're recording the user that created/updated the record. I note that the patient_attachments proposed endpoint also contains this field.

Cheers

**Comment by JohnColvin** [comment]
This isn't something that we'd be able to easily flip on for all resources. We don't universally hold this info on the record itself like we do with the timestamps. The resources that do have that field were created with an "author" type relationship to the user that created it. I didn't confirm, but my guess would be that every API resource that has that data is already exposing it.

To do this right, we'd need to decide if we want to put it on all records, or expose all the version records that have the entire change history, or both. Then there's the added issue that we wouldn't be able to backfill the creator on records that existed before that table was versioned.

That is all to say, it's a complicated landscape of data for this and we'd probably take the time to formalize how the API expresses this.

**Comment by hagen** [comment]
It's got my +1(,000,000)

**Comment by bpinto** [comment]
Going to close this issue there isn't anything we can do at this moment.
