### ISSUE TITLE
Possible to get available times for any practitioner at a business between dates?

### ISSUE THREAD

**Issue by jontycg** [redguava/cliniko-api#198]
The docs show how to get available times for a given practitioner between 2 dates but is it possible to get all available times for a business from all of the practitioners at that business or do you have to specify a practitioner?

**Comment by bpinto** [comment]
You have to specify a practitioner. This is a very heavy end point, not sure at this moment if we will eventually drop this requirement in a future or not.

**Comment by JohnColvin** [comment]
To get all the availabilities for all the practitioners at a business, you'll need to loop through all the pracs and do a request for each of them.

**Comment by jontycg** [comment]
Appreciate you guys getting back to me so soon. Consider this a +1 for a feature where you can get all business availabilities with one request.
