### ISSUE TITLE
Filtering on non-filterable fields returns 'Unexpected T'

### ISSUE THREAD

**Issue by hagen** [redguava/cliniko-api#203]
Filtering on a non-filterable field for an entity returns 400 with response
`Unexpected 'T'`

**Comment by bpinto** [comment]
This was an oversight from our part. The response body is not a valid JSON object even when you ask for a `application/json` content type.

We are probably going to fix this by sending a valid JSON object in the response body.

**Comment by bpinto** [comment]
We are now returning JSON objects in the response body, this should fix your parsing error. :+1:
