### ISSUE TITLE
Return archived and deleted patients

### ISSUE THREAD

**Issue by nicholasmott** [redguava/cliniko-api#21]
Currently archived and deleted patients are not returned by the Get /patients endpoint.

For integrations attempting to keep patient lists in sync this results in orphaned patients. The original creation is sent but the archive/deletion never is.

Can you provide endpoints for archived/deleted patients in the same way that appointment cancellations/deletions are provided.

**Comment by bpinto** [comment]
This functionality has now been done, thanks for the patience.

**Comment by nicholasmott** [comment]
Thanks guys. I will try it all out in the near future.
