### ISSUE TITLE
Add or convert to Swagger documentation

### ISSUE THREAD

**Issue by jradtilbrook** [redguava/cliniko-api#213]
Would you consider either adding a Swagger specification (YAML or JSON) or swapping over to it? If you aren't aware, it is an amazing tool that allows you to describe an API in a single file and then generate documentation and integration clients in many different languages. You could even leverage GitHub pages to host it. In my opinion, it would vastly improve the documentation efforts in this repo and also allow clients to generate code in whatever language they are using.

Check out the [documentation](https://swagger.io/)

I'd be happy to make a start with a PR but documenting the whole API is quite an undertaking.

**Comment by bpinto** [comment]
I have looked at it many times, thought about starting it, but never actually started it.

Since I have not used it, what do you think we would lose with this change (if anything)?

**Comment by jradtilbrook** [comment]
First off, I think there's a lot to gain as I mentioned above, which may outweigh the cons - at least from an integrator perspective.  
The main thing I can think of is that it uses a single file for the entire API by default, but you can have references to other files for parts of it so I think that might not be an issue (see [this issue](https://github.com/swagger-api/swagger-editor/issues/233)). Depending on how your team manages contributions, the chance of conflicts might increase if you use a single file.  
The other thing I can think of might be a little harder to maintain or go into the amount of detail you currently have with the separate markdown files, although possible it might get a little messy in the swagger yaml/json format.

**Comment by jradtilbrook** [comment]
No worries. I should have some time in the next few weeks to flesh something out. I'll probably leave the majority to you, but make a start on the base file and setting up tooling to help

**Comment by hagen** [comment]
@jradtilbrook definitely keen to convert the API docs to something more useful. This is on the radar now. I'll close this issue as we *will* be doing this.

**Comment by jradtilbrook** [comment]
That's awesome!  
And sorry I completely forgot about this but glad to here it's happening :+1:
