### ISSUE TITLE
Returning related Ids

### ISSUE THREAD

**Issue by Liam-Tait** [redguava/cliniko-api#216]
I would like to request that links also return the associated ids as siblings to the links

Specifically for `https://api.cliniko.com/v1/unavailable_blocks`

I would like to  add the `practitioner_id` and `business_id` to the returned JSON
this prevents requiring calling links in order to ingress this data.

**Comment by bpinto** [comment]
@Liam-Tait we don't intend to change the existing `links` format. If you need the IDs however, you can parse the link and get the IDs from them.
