### ISSUE TITLE
Concessions

### ISSUE THREAD

**Issue by Aristarkh4** [redguava/cliniko-api#217]
Is it possible to add the Student and Elderly concession fields to the billable items request?

**Comment by bpinto** [comment]
It shouldn't be a hard entry point to create, but we are overwhelmed with some other feature at the moment, so I don't think we have the time right now to work on this end point.

**Comment by Aristarkh4** [comment]
@JohnColvin yes, that's exactly what I was looking for.

**Comment by JohnColvin** [comment]
Closing since this is a duplicate of #201
