### ISSUE TITLE
Update concession type via API?

### ISSUE THREAD

**Issue by purerdm** [redguava/cliniko-api#227]
I'm trying to update the referring_doctor field for patients via API. Updates for other fields are working successfully. Can this field be updated via API? Not getting error messages, so not sure if it's just a syntax issue or a gap in the API.

If this can't be done, can this be considered for enhancement?

**Comment by purerdm** [comment]
Hello? Any signs of life?

**Comment by sas1ni69** [comment]
Hi @purerdm sorry for the late reply. Referring doctor cannot be updated via the API for now. I'll chat to the rest of the team and let you know if we can add this soon.

**Comment by purerdm** [comment]
I think the same issue exists for the concession_type field. Can you confirm? This would be another that would be handy to bulk-update during migrations.

**Comment by purerdm** [comment]
Ping? I can see that concession_type is an included field that can be mapped during an import, so I'm not completely sure if it's the same issue. However the Import feature cannot be used to update (they create new patients, not update existing ones) so I think I'm stuck again...

**Comment by JohnColvin** [comment]
Hey @purerdm. Sorry about the slow responses. Several of us took some time off after the big GDPR push.

I don't think there's any particular reason why those 2 fields shouldn't be assignable via API. I'll confirm with the rest of the team and get a PR up to add them.

**Comment by JohnColvin** [comment]
We added the ability to set referring doctor via API today.

I'm going to rename this issue to be a request to set concession type.

**Comment by purerdm** [comment]
Great stuff! Really appreciate you jumping in and improving this. I'm having issues getting it to work though, can you drop an example here? Not getting syntax errors so I assume I'm getting the syntax right, but not getting an update. 

Thanks again!

**Comment by JohnColvin** [comment]
The param is `referring_doctor_id` is that what you're sending?

**Comment by purerdm** [comment]
Ahhh... that worked. Excellent! :)

**Comment by purerdm** [comment]
Any ETA on concession types via the API?

**Comment by JohnColvin** [comment]
Sorry, nothing to report yet.

**Comment by purerdm** [comment]
Anyone alive here????

**Comment by JohnColvin** [comment]
Sorry for leaving you hanging! You can now set `concession_type_id` for patients via the API.
