### ISSUE TITLE
400 Error when calling deleted patients with updated_at filter

### ISSUE THREAD

**Issue by nicholasmott** [redguava/cliniko-api#231]
Hi team,

I'm getting a 400 error response when calling the deleted patients end point with an updated_at filter.

The message returned is {"message":"This column is not searchable."}

The call is:

`curl "https://api.cliniko.com/v1/patients/deleted?q[]=updated_at:>2018-05-14T14:00:08Z" -g -u xxxxxxxxxxxxxxx: -H 'Accept: application/json' -H 'InstinctiveNotes (support@instinctivenotes.com)' `

Could you please look into it.

Cheers,
Nick

**Comment by hagen** [comment]
Hi Nick - any endpoint that is /deleted, can only be queried using `deleted_at` or `id`

**Comment by nicholasmott** [comment]
Interesting. The documentation suggests otherwise, that any patient endpoint that returns a set of patients can be filtered by updated_at.

Also it's possible to filter deleted appointments by `starts_at` so your comment doesn't hold true for all endpoints.

I've also noticed that the response to the unfiltered `patients/deleted` endpoint sends different records than documented under the "Get Deleted Patients" heading. It no longer sends a full patient record, only some limited details (id, deleted_at).

I did some pretty extensive testing when I put this endpoint in. Did something change at some point?

I'm happy to make a change to use `deleted_at` if necessary but I'd like to check and see if this is what is expected before I do so.

**Comment by hagen** [comment]
You'll want to read up on the changes that were implemented to support GDPR. Over on the Google Groups.
https://groups.google.com/a/redguava.com.au/forum/#!searchin/cliniko-api/gdpr%7Csort:date

**Comment by hagen** [comment]
Specifically this part Nick:

> The resources that will no longer serve data on their deleted endpoints are:
> - appointments
> - attendees
> - bookings
> - group appointments
> - individual appointments
> - medical alerts
> - patients
> - treatment notes
> - unavailable blocks

**Comment by nicholasmott** [comment]
Right you are.

Looks like I have some work to do.

Thanks for the assist.

**Comment by hagen** [comment]
No problemo. There's a bit of a disconnect between where information surfaces for us 3rd parties. Google Groups is good because it pings everyone in the group, but if you're not in the group - or don't check those emails - it's easy to miss updates. Good luck.

**Comment by jfriedlaender** [comment]
If anyone has suggestions on how we can better communicate, please do let
us know.

**Comment by nicholasmott** [comment]
@jfriedlaender I've subscribed to updates from the Google Group which I probably should have done some time ago. Other than that I'm not sure there's anything specific to do.

I missed the updates as work on the Cliniko API tends to be chunky, some focused time followed by a period of nothing, so I really only dig into the changes when it's time to do something Cliniko related.
