### ISSUE TITLE
Set Referral Type to pre-defined value for new patients

### ISSUE THREAD

**Issue by digime99** [redguava/cliniko-api#234]
Hi there

I've seen related posts on this topic but just wanted to confirm, is there any way to set Referral Type to a pre-defined value for new patients via the API?

If we POST a value for referral_source, that value appears when you view the patient, however if you edit the patient, "Referral Type" is "None" and the value we submitted displays in "Extra Information".

Thanks

**Comment by hagen** [comment]
Hi @digime99 - currently the Cliniko API only supports setting the `referral_source` to a string value, which as you pointed out, is displayed in _Extra information_. Supplying a `referral_ type` is not currently supported.

As for the inconsistency when _editing_ a patient, we should be setting the type to `Other` when saving the patient. I'll confirm that this is something we can fix up and push out.

**Comment by metabren** [comment]
> As for the inconsistency when editing a patient, we should be setting the type to Other when saving the patient. I'll confirm that this is something we can fix up and push out.

Would love for this to be applied retroactively as well.

**Comment by hagen** [comment]
Referral source type will be automatically set to 'Other' when supplying a `referral_source` text in POST/PUT to `/patients/:id`, **where there is no referral source type currently set**.
This does not affect referral sources against patients that have had a referral source type set, either through the UI or through `/patients/:id/referral_source`. We're also updating patients that have a referral source text but no referral source type, to have the referral source type of 'Other' (this may take some time to finish running).
