### ISSUE TITLE
I am not able to list Available Times getting 404

### ISSUE THREAD

**Issue by Hitendrachopda** [redguava/cliniko-api#245]
Please check URL format: https://api.cliniko.com/v1/businesses/70942/practitioners/110727/appointment_types/328283/available_times/?from=2018-12-03&to=2018-12-04

My API KEY correct because I am running same API KEY to this url: https://api.cliniko.com/v1/practitioners/
And it works fine.

Please check this issue and let me know how I can fixed it.

My User email is: lana@doctors.com.au

Thanks,

**Comment by Billiam** [comment]
Hi! The business in your url (`70942`) doesn't have online booking enabled, resulting in a 404. Hope that helps!
