### ISSUE TITLE
Bug: Available Times API is showing practitioners not enabled for appointment type

### ISSUE THREAD

**Issue by niraj-shah** [redguava/cliniko-api#248]
I am building a Cliniko integration for a client and have discovered a issue with the `available_times` API:

```
GET /businesses/:business_id/practitioners/:practitioner_id/appointment_types/:appointment_type_id/available_times?from=DATE&to=DATE
```

The client has 4 practitioners, who are part of the clinic, but each has different specialities. Some of the appointment types can only be dealt by 1-2 of the practitioners.

When requesting availability for a particular appointment type (lets call it 1234), I called the API as follows:

1. /businesses/:business_id/practitioners/1111/appointment_types/1234/available_times?from=DATE&to=DATE
2. /businesses/:business_id/practitioners/2222/appointment_types/1234/available_times?from=DATE&to=DATE
3. /businesses/:business_id/practitioners/3333/appointment_types/1234/available_times?from=DATE&to=DATE
4. /businesses/:business_id/practitioners/4444/appointment_types/1234/available_times?from=DATE&to=DATE

I.e. I cycles through the list of practitioners, and got the available slots for the 1234 appointment type.  I was expecting the API call for practitioner `3333` to fail as this practitioner does not deal with this appointment type. However, the API in fact returned to be free slots.

This means the preferences in the Cliniko settings are not being respected in this particular API.

**Comment by bpinto** [comment]
@niraj-shah we were able to reproduce this bug and a fix will be released soon.

**Comment by niraj-shah** [comment]
Thanks @bpinto. Any ETA on when the fix would be available?

**Comment by bpinto** [comment]
Sorry, this got closed automatically on commit. This fix is already live.
