### ISSUE TITLE
Cannot write to `gender_identity` field via API

### ISSUE THREAD

**Issue by lionsdwarf** [redguava/cliniko-api#249]
Repro: Create or Update a Patient record via the API and specify a value for `gender_identity`
Result:  The `gender_identity` field returns `null`
Expected result: The `gender_identity` field contains the value specified in the write call

**Comment by JohnColvin** [comment]
We just started accepting the `gender_identity` param. Thanks for poking us about it!

**Comment by lionsdwarf** [comment]
👍 Thank *you* @JohnColvin !
