### ISSUE TITLE
Available Appointment Times by Patient?

### ISSUE THREAD

**Issue by niraj-shah** [redguava/cliniko-api#250]
Is there anyway to find the available appointment slots by patient (for a particular appointment type), so that potential conflicts with the same patient are avoided?

For example, if there are multiple practitioners providing different therapies, the patient may want to book several different appointments on the same day, each for a different therapy. However, at the moment this could mean the patient's appointments could overlap or conflict with their own.

**Comment by bpinto** [comment]
This is not something we have built, you would have to do the business logic yourself using the [AvailableTimes](https://github.com/redguava/cliniko-api/blob/master/sections/available_times.md), [Bookings](https://github.com/redguava/cliniko-api/blob/master/sections/bookings.md) end points to create slots per appointment type and then allocate the patient.
