### ISSUE TITLE
Unable to update pronouns

### ISSUE THREAD

**Issue by jacquelyn-tandang** [redguava/cliniko-api#256]
json_encoded the following data:

array (size=2)
  'gender_identity' => string '"Male", "Man"' (length=13)
  'pronouns' => 
    array (size=5)
      'reflexive' => string 'himself' (length=7)
      'accusative' => string 'him' (length=3)
      'nominative' => string 'he' (length=2)
      'pronominal_possessive' => string 'his' (length=3)
      'predicative_possessive' => string 'his' (length=3)

'{"gender_identity":"\"Male\", \"Man\"","pronouns":{"reflexive":"himself","accusative":"him","nominative":"he","pronominal_possessive":"his","predicative_possessive":"his"}}' 

However, when I visit the patient's page after the update patient call,
The gender_identity gets updated but pronouns field stays null.
The API response does not return any error. It returns an updated patient data with pronouns field null

Any idea why?

**Comment by JohnColvin** [comment]
We don't currently allowing assignment of pronouns via API. I've asked the rest of the team their opinions about allowing them to be set.

**Comment by JohnColvin** [comment]
We've added the ability to set pronouns via API.

I'm curious about what you're setting for gender identity. I'd expect `sex` to be set to `Male` and `gender_identity` set to `Man`.
