### ISSUE TITLE
Base64 encode in not working with my account

### ISSUE THREAD

**Issue by xsteacy** [redguava/cliniko-api#257]
I have created a new account(trial) and generated an API key from it, everything is working fine.
I used [https://www.base64encode.org/](https://www.base64encode.org/) to encode both.
The trial is ok and it finishes with == when I encode it.
With my real account, it's not.

-I tried adding a new user for a new API key
-I tried multiple times with other encoders and API keys.

Any help is much welcome
Thank you very much

**Comment by hagen** [comment]
I'm sure there's a simple explanation 😊- would you mind posting a code sample too @xsteacy?
Ideally, a [Minimal, Complete and Verifiable](https://stackoverflow.com/help/mcve) sample, so as to reproduce your problem exactly.

Finally, if you have [Postman](https://www.getpostman.com/), try invoking your request from there also. Once your request is working in Postman, you may also use Postman to generate code stubs for many popular languages.

**Comment by xsteacy** [comment]
```
function dataOut() {


  var options = {
    "headers" : {
      "Authorization" : "Basic MY_ENCODED_API_KEY",
      "Accept" : "application/json",
      "User-Agent": "GoogleAppsScript (my@email.com)"
  }
};
  var response = UrlFetchApp.fetch("https://api.cliniko.com/v1/patients", options);
    Logger.log(response.getContentText());
};
```

But like I said... It works with the trial account... so it's not coding problems. Oh and it's from google apps script

**Comment by hagen** [comment]
Thanks!

When trying with your live account, is there an error code or error message returned from within the Apps Script? That might very quickly explain what the problem is.

Could you try with Postman on your real account? If that works, then there's something up in your Apps Script.

**Comment by xsteacy** [comment]
There is an error when I put my encoded key:
Request failed for https://api.cliniko.com/v1/patients returned code 401 (line 10, file "test")

I just tried with Postman with both accounts, again it's only working with the trial account like on the script

p.s. This is an example of the encoded key, you probably understand more...(I just changed a couple of letters/numbers but that's the idea:
1-14576-7LaCKZQpH2hWl4tffkfbxm58zJV2Wgki

**Comment by xsteacy** [comment]
I just learned a new thing, If I create an API_KEY with an account that doesn't have access to patients(for example) They will get errors. But, I do have access to patients ;)

**Comment by xsteacy** [comment]
OMG!
I found a way to get rid of my problem, that's kinda weird but it works.
I use Firefox instead of Chrome to copy paste the API-KEY and voila!
I use Fedora 29 if that can be of any help.

**Comment by hagen** [comment]
Great 👍 Maybe there was an extra space character in there, or something like that.
So you're all good now?
