### ISSUE TITLE
Cannot find archived / deleted appointment types

### ISSUE THREAD

**Issue by sahutchings** [redguava/cliniko-api#259]
Hi,
I can see links to appointment_types in the appointments end point, but when I try to find information (or connect) to that link I get a 404 - Not Found.
Does this mean we do not have access to appointment_types/deleted records? If so, why is this and can we please get access.
We have recently made a number of changes to out Appointment Types and it is making it very difficult to do historical analysis of our appointments.
Thank you

**Comment by hagen** [comment]
It may be that the API key you're using belongs to a user that doesn't have access to `appointment_types` (i.e. settings). Try with another API key (either _power receptionist_ or _administrator_ if these are options for you) and see how you get on.

**Comment by hagen** [comment]
Assume resolved. Closing.
