### ISSUE TITLE
Filtering contacts by email

### ISSUE THREAD

**Issue by APIANT** [redguava/cliniko-api#260]
I need to be able to lookup a contact by email.

**Comment by hagen** [comment]
Hi there - contacts aren't filterable on email address.

**Comment by APIANT** [comment]
I see that.  It's a feature request.

In general, filterable fields are few and far between, doesn't make the API very useful for finding data.

**Comment by hagen** [comment]
Thanks for the feature request - we'll look at adding that in shortly and comment here when it's done!

**Comment by hagen** [comment]
`/contacts` are now filterable by email. Standard string filter operands apply; the filter is automatically applied to a lowercased version of the email address.
Enjoy!

**Comment by APIANT** [comment]
Thank you very much, looks to be working great!
