### ISSUE TITLE
New patient isn't being created on POST w/ cURL

### ISSUE THREAD

**Issue by jamesjoegraham** [redguava/cliniko-api#261]
Hi there!

I'm creating an application using the cliniko API, and am trying to create a patient with the cURL command example from the patients documentation:

`curl https://api.cliniko.com/v1/patients/ -u MY_API_KEY: -H 'Content-Type: application/json' -H 'User-Agent: James_Graham (jamesgrahamemail@email.com)' -d '{ "first_name": "Tester", "last_name": "McTestFace"  }' -X POST`

AFAIK the only requirements for creation of a new patient are first_name and last_name, however I get this response:

`{"message":"Validation Failed","errors":{"first_name":"canΓÇÖt be blank","last_name":"canΓÇÖt be blank"}}`

Telling me that I left the fields blank. Would greatly appreciate any assistance.

Thanks,

James

**Comment by JohnColvin** [comment]
Hi James,

I copied your command and swapped in my own API key and it worked. So, I'm
not sure exactly how to help. If you're having issues with curl, I'd try
postman. I normally user postman over curl because it's a user friendly GUI.

Best,
John

**Comment by jamesjoegraham** [comment]
Was an issue with cURL, thanks for your time!
