### ISSUE TITLE
Name cannot be Blank when creating Notes Template

### ISSUE THREAD

**Issue by Taylorsuk** [redguava/cliniko-api#263]
Attempting to create a notes template at `https://api.cliniko.com/v1/treatment_note_templates` is returning: `body: "{"message":"Validation Failed","errors":{"name":"can’t be blank"}}"` 

```
{
  "name": "My Notes Template",
  "content": {
    "sections": [
      {
        "name": "PrescriptionID",
        "questions": [
          {
            "name": "Prescription ID",
            "type": "text"
          },
          {
            "name": "Prescription URL",
            "type": "paragraph"
          }
        ]
      }
    ]
  }
}
```

The JSON above is created as per the [docs](https://github.com/redguava/cliniko-api/blob/master/sections/treatment_note_templates.md#create-treatment-note-template). Unsure if there is an issue or my method is wrong?

**Comment by hagen** [comment]
Hi Simon,

I just ran that same query against Cliniko - worked for me.

**Comment by bpinto** [comment]
@Taylorsuk are you perhaps not encoding it in json correctly? It's possible that we are not parsing any of the json.

**Comment by Taylorsuk** [comment]
@bpinto, @hagen - many thanks for the heads up about JSON being correct. There was an issue with `request.js` sending it as a string, I needed to set the json option to true (https://www.npmjs.com/package/request)

Many thanks for being helpful and friendly!
