### ISSUE TITLE
Question on this field "receives_confirmation_emails"

### ISSUE THREAD

**Issue by fcbaconguis** [redguava/cliniko-api#265]
I have been scanning the api of where this field **patient[receives_confirmation_emails]** is saved, can you provide the correct name on the api? Thank you.

**Comment by hagen** [comment]
Hi there!
This prop isn't exposed on /patients. The reminder_type prop is however,
which can be set to one of four options: null, SMS, Email, SMS & Email.
I'll follow up with the team to see if there's a reason we're not
sending/accepting this property.

Cheers!

**Comment by fcbaconguis** [comment]
Hi hagen,

For clarification.

Automated reminder type -> **reminder_type** field
Agrees to receive your promotional SMS marketing -> **accepted_sms_marketing** field
Receive booking confirmation emails -> **this third field is my question, what field is this saved?**

Thanks!

Fritz

**Comment by hagen** [comment]
We don't currently expose that property on the patients endpoint. Discussing internally whether we can add it (should be okay!)
What specifically do you need it for @fcbaconguis ?

**Comment by fcbaconguis** [comment]
hi @hagen, I am tasked to manage the patient details, one of them is to reset the communication preferences into "None" or null or untick that setting.

**Comment by hagen** [comment]
Are you attempting to trigger a reset of comms preferences from another application? And how often would this need to be done?
Or is this a _bulk_  type operation?

**Comment by fcbaconguis** [comment]
Yes, by using the api

this will be triggered once for now and depends if tasked again to do it again in the next few months

Yes this is a bulk type operation.

**Comment by hagen** [comment]
I think we're good to add `receives_confirmation_emails` to `/patients`. Stay tuned.

**Comment by hagen** [comment]
@fcbaconguis this prop is now in `/patients` - enjoy!
