### ISSUE TITLE
Can't set "Reference number" and "Referring doctor" on new patients

### ISSUE THREAD

**Issue by digime99** [redguava/cliniko-api#267]
Hi there

We'd like to be able to set "Reference number" and "Referring doctor" when adding new patients.

"Reference number" doesn't appear to be exposed in the API.

"Referring doctor" is, and we can read it, but passing a value similar to below for POST/PUT seems to be ignored...

"referring_doctor": {
        "links": {
          "self": "https://api.cliniko.com/v1/contacts/123"
        }
      }

Can you confirm?

**Comment by hagen** [comment]
Hi! Sorry for the delay.
The _reference number_ displayed in Cliniko is the property `old_reference_id` in the `/patients` endpoint.

**Comment by digime99** [comment]
ok great, thanks!

What about "Referring doctor" - are we able to set that, or is it read-only?

**Comment by hagen** [comment]
Sorry - I missed that part of your query.
Referring doctor is:
```
POST /patients
{
  "referring_doctor_id": <ID_OF_A_DR_CONTACT>,
  "old_reference_id": "A6549873",
  ...
}
```

**Comment by digime99** [comment]
awesome, thanks!
