### ISSUE TITLE
BUG!  Get Patients API is broken - returning 500s

### ISSUE THREAD

**Issue by rdrenker** [redguava/cliniko-api#271]
Attempting to call **https://api.cliniko.com/v1/patients** is returning a 500.

Note that retrieving individual patient records (ie: https://api.cliniko.com/v1/patients/123456) works, however attempting to retrieve the entire list of patients fails.

**Comment by hagen** [comment]
Thanks for the issue! We're looking into this now. Will post back here with more.

**Comment by hagen** [comment]
The `/v1/patients` endpoint should be responding normally now, sorry for the inconvenience. Thanks for letting us know!
