### ISSUE TITLE
Cliniko Appointment Creation datetime Error 

### ISSUE THREAD

**Issue by SandeepDevSri** [redguava/cliniko-api#272]
Dear Cliniko Support Team,

Please find the below response from your side for the appointment created on our account.

Appt Start Time in EST : Thu, 12 Sep 2019 10:00:00 +1000
Start Datetime sent in UTC to Cliniko : 2019-09-12 00:00:00
Appt End Time in EST : Thu, 12 Sep 2019 10:30:00 +1000
End Datetime sent in UTC to Cliniko : 2019-09-12 00:30:00

But in response, it is saying it created an appt at 2019-09-11T23:00:00
In the account it says it is between 9am to 9.30 am one hour difference

Also each time we create an appointment from through the api it gets created but many times time at which it would be created will be different from the one we requested. Can you please provide a solution for the same please. 

Response from your api

Array
(
    [id]=>175287125
    [created_at]=>2019-09-03T08:47:53Z
    [updated_at]=>2019-09-03T08:47:53Z
    [booking_ip_address]=>
    [cancellation_note]=>
    [cancellation_reason]=>
    [conflicts]=>Array
        (
            [links]=>Array
                (
                    [self]=>https://api.cliniko.com/v1/appointments/175287125/conflicts
)

)

    [did_not_arrive]=>
    [email_reminder_sent]=>
    [invoice_status]=>
    [notes]=>dsf
    [online_booking_policy_accepted]=>
    [patient_arrived]=>
    [patient_name]=>Adam Test
    [repeat_rule]=>Array
        (
)

    [repeats]=>
    [sms_reminder_sent]=>
    [treatment_note_status]=>
    [appointment_start]=>2019-09-11T23:00:00Z
    [appointment_end]=>2019-09-11T23:30:00Z
    [deleted_at]=>
    [cancellation_time]=>
    [archived_at]=>
    [cancelled_at]=>
    [ends_at]=>2019-09-11T23:30:00Z
    [starts_at]=>2019-09-11T23:00:00Z
    [appointment_type]=>Array
        (
            [links]=>Array
                (
                    [self]=>https://api.cliniko.com/v1/appointment_types/394928
)

)

    [business]=>Array
        (
            [links]=>Array
                (
                    [self]=>https://api.cliniko.com/v1/businesses/81566
)

)

    [practitioner]=>Array
        (
            [links]=>Array
                (
                    [self]=>https://api.cliniko.com/v1/practitioners/130029
)

)

    [patient]=>Array
        (
            [links]=>Array
                (
                    [self]=>https://api.cliniko.com/v1/patients/59306188
)

)

    [attendees]=>Array
        (
            [links]=>Array
                (
                    [self]=>https://api.cliniko.com/v1/appointments/175287125/attendees
)

)

    [invoices]=>Array
        (
            [links]=>Array
                (
                    [self]=>https://api.cliniko.com/v1/appointments/175287125/invoices
)

)

    [links]=>Array
        (
            [self]=>https://api.cliniko.com/v1/appointments/175287125
)

)

**Comment by SandeepDevSri** [comment]
Thanks John for your reply. 
We tired sending the datetime as suggested by you. We were trying to create an appointment on 20th Sep 2019 between 2pm to 2.15pm. 
In the response we have got it correctly 
[appointment_start]=>2019-09-20T14:00:00Z
[appointment_end]=>2019-09-20T14:15:00Z
But in the Cliniko Portal it shows appointment created at 10pm on 20th September. 
https://www.screencast.com/t/rnHcUfS2g2b
Below is the response for your further analysis. 
Array
(
    [id]=>176980715
    [created_at]=>2019-09-13T07:13:37Z
    [updated_at]=>2019-09-13T07:13:37Z
    [booking_ip_address]=>
    [cancellation_note]=>
    [cancellation_reason]=>
    [conflicts]=>Array
        (
            [links]=>Array
                (
                    [self]=>https://api.cliniko.com/v1/appointments/176980715/conflicts
)

)

    [did_not_arrive]=>
    [email_reminder_sent]=>
    [invoice_status]=>
    [notes]=>test appointment
    [online_booking_policy_accepted]=>
    [patient_arrived]=>
    [patient_name]=>Adam Test
    [repeat_rule]=>Array
        (
)

    [repeats]=>
    [sms_reminder_sent]=>
    [treatment_note_status]=>
    [appointment_start]=>2019-09-20T14:00:00Z
    [appointment_end]=>2019-09-20T14:15:00Z
    [deleted_at]=>
    [cancellation_time]=>
    [archived_at]=>
    [cancelled_at]=>
    [ends_at]=>2019-09-20T14:15:00Z
    [starts_at]=>2019-09-20T14:00:00Z
    [appointment_type]=>Array
        (
            [links]=>Array
                (
                    [self]=>https://api.cliniko.com/v1/appointment_types/394928
)

)

    [business]=>Array
        (
            [links]=>Array
                (
                    [self]=>https://api.cliniko.com/v1/businesses/81566
)

)

    [practitioner]=>Array
        (
            [links]=>Array
                (
                    [self]=>https://api.cliniko.com/v1/practitioners/130029
)

)

    [patient]=>Array
        (
            [links]=>Array
                (
                    [self]=>https://api.cliniko.com/v1/patients/59306188
)

)

    [attendees]=>Array
        (
            [links]=>Array
                (
                    [self]=>https://api.cliniko.com/v1/appointments/176980715/attendees
)

)

    [invoices]=>Array
        (
            [links]=>Array
                (
                    [self]=>https://api.cliniko.com/v1/appointments/176980715/invoices
)

)

    [links]=>Array
        (
            [self]=>https://api.cliniko.com/v1/appointments/176980715
)

)
Ok

**Comment by hagen** [comment]
Hi @SandeepDevSri 

as John said, the timestamps you send to Cliniko need to be in UTC, so you should convert your local time timestamp, to a UTC timestamp, and send that to Cliniko. If you want the appointment to start at 20 Sep, 2pm (AEST), the date time needs to be converted to its UTC equivalent first.
e.g. Converting an Australian AEST date time to UTC, runs as follows, subtracting 10 hours from the time:
> 2019-09-20 **14:00:00 (AEST)** => 2019-09-20T**04:00:00Z**

It's important to remember that the appointment will be displayed in the Cliniko account's timezone. So an appointment created with a `starts_at` value of **2019-09-20T04:00:00Z** will be displayed in the calendar as Sep 20, 2pm.

If you're using PHP (?), this may be of use:
https://stackoverflow.com/questions/2095703/php-convert-datetime-to-utc

**Comment by SandeepDevSri** [comment]
Thanks very much Hagen, we were able to resolve this issue. Thanks again
