### ISSUE TITLE
Cancel Appointments API is returning 404

### ISSUE THREAD

**Issue by SandeepDevSri** [redguava/cliniko-api#273]
Dear Support Team, 

We are trying to set up cancel appointments through API but getting 404 error. We are able to push in the status but cancellation is not working. 
Here are the input parameters we are sending & response we are getting. Any help would be highly appreciated. 

Input Parameters 
Array
( [cancellation_note]=>Cliniko Cancel Note 
  [cancellation_reason]=>10
)
We are trying to call this API url to cancel appointments. 
https://api.cliniko.com/v1/individual_appointments/177090725/cancel

Response we have got is as follows 
HTTP/1.1 404 Not Found
Content-Type:text/html;charset=utf-8
Server:nginx
Strict-Transport-Security:max-age=15552000;includeSubDomains;preload
X-Request-Id:d4e61dc6-a3d6-499a-aaf1-2adb2cb29867
X-Runtime:0.002769
Content-Length:27786
Accept-Ranges:bytes
Date:Thu, 19 Sep 2019 08:21:23 GMT
Via:1.1 varnish
Connection:keep-alive
X-Served-By:cache-mel19031-MEL
X-Cache:MISS
X-Cache-Hits:0
X-Timer:S1568881283.225113,VS0,VE19
Vary:Accept-Encoding<!DOCTYPE html><html><head><meta charset="utf-8"><meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Cliniko - 404</title></head><body class="index"><div class="page-content"><h1>The page you’re looking for doesn’t exist.</h1><p>Well, technically it might exist but it isn’t here. You can press the back button on your browser to return to the previous page, or <a href='/'>magically teleport</a>straight to Cliniko.</p></div></body></html>

**Comment by JohnColvin** [comment]
Hi Sandeep,

What HTTP method are you using when hitting that route? The cancel route
uses the PATCH method.

Cheers,
John

**Comment by hagen** [comment]
Closing, assumed resolved. Please reopen if not.
