### ISSUE TITLE
BUG - Treatment Note API filtering broken - only obeys the last parameter

### ISSUE THREAD

**Issue by rdrenker** [redguava/cliniko-api#274]
If I query the treatment note API by **practitioner**, I get expected results, ie:

https://api.cliniko.com/v1/treatment_notes?q=practitioner_id:=12345

if I query the API by **created_at** date, I also get expected results, ie:

https://api.cliniko.com/v1/treatment_notes?q=created_at:>2019-09-15T00:00:00Z

However if I attempt to query by both, it ignores the first query parameter and only filters by the last one.

For example, if **practitioner** is first, and **created_at** second, I will get treatments for **all** practitioners created after 2019-09-15:
https://api.cliniko.com/v1/treatment_notes?q=practitioner_id:=12345&q=created_at:>2019-09-15T00:00:00Z

On the other hand if **practioner** is second and **create_at** is first, then I will get all treatment notes for the practitioner, regardless of the creation date:
https://api.cliniko.com/v1/treatment_notes?q=created_at:>2019-09-15T00:00:00Z&q=practitioner_id:=12345

**Comment by JohnColvin** [comment]
Hi there! You need to send an array of filters using the `q[]` syntax

https://api.cliniko.com/v1/treatment_notes?q[]=created_at:%3E2019-09-15T00:00:00Z&q[]=practitioner_id:=12345

**Comment by rdrenker** [comment]
Quite right - I was just about to go and delete this issue, but you got to it so quickly I didn't have a chance!

Thanks for the quick response!
