### ISSUE TITLE
Adding internal admin product integration

### ISSUE THREAD

**Issue by craigspaeth** [redguava/cliniko-api#276]
Hello,

We have an internal admin page for patients at [Octave](http://findoctave.com) that we would like to use Cliniko's connected apps for. I contacted your support team through Intercom and they said we need to open an issue here to be approved (otherwise we see a "This URL is not trusted" error).

This would be an internal-only product—so not a public integration meant to be advertised on your integrations page. The URL we want to support is https://www.findoctave.com/admin

Let me know how best to proceed.

Thanks!

**Comment by hagen** [comment]
Hi Craig - I'll email you separately.
