### ISSUE TITLE
Can we rely on business.appointment_type_ids?

### ISSUE THREAD

**Issue by craigspaeth** [redguava/cliniko-api#277]
We're referring to the `appointment_type_ids` field returned from [business resource](https://github.com/redguava/cliniko-api/blob/master/sections/businesses.md) and noticed it's not [documented](https://github.com/redguava/cliniko-api/blob/master/sections/businesses.md#get-businesses). Can we rely on this or should we refactor it to grab the appointment types in a different way? If the latter, what would you recommend is the way to query for this... business > practitioners > practitioner.default_appointment_type ?

**Comment by bpinto** [comment]
You can rely on `business.appointment_type_ids` for getting the list of appointment types associated to a business.

That is not the same as the list of appointment types associated to a practitioner.

![2019-10-18-112437](https://user-images.githubusercontent.com/526122/67086974-e5d8ed00-f199-11e9-8272-188e03af0eb4.png)

**Comment by hagen** [comment]
Answered?
