### ISSUE TITLE
Available times endpoint doesn't respect unavailable blocks

### ISSUE THREAD

**Issue by craigspaeth** [redguava/cliniko-api#279]
When I set unavailable blocks in Cliniko and query the [available times](https://github.com/redguava/cliniko-api/blob/master/sections/available_times.md) endpoint I get back a bunch of available times that overlap with the unavailable blocks.

This is in our https://staging-octave.cliniko.com account. Here's the endpoint I'm hitting:

```
GET https://api.cliniko.com/v1/businesses/81977/practitioners/108233/appointment_types/394354/available_times?from=2019-11-28&to=2019-11-29 
```

Screenshot of the unavailable blocks (ET timezone preferences):

![image](https://user-images.githubusercontent.com/555859/67717958-23f9bc00-f9a5-11e9-843e-b8a8de859e7f.png)

Practitioner `108233` only offers the one appointment type `394354`.

Here's the data I get back:

```
{
  available_times: [
    { appointment_start: '2019-11-28T17:00:00Z' },
    { appointment_start: '2019-11-28T17:30:00Z' },
    { appointment_start: '2019-11-28T18:00:00Z' },
    { appointment_start: '2019-11-28T18:30:00Z' },
    { appointment_start: '2019-11-28T19:00:00Z' },
    { appointment_start: '2019-11-28T19:30:00Z' },
    { appointment_start: '2019-11-28T20:00:00Z' },
    { appointment_start: '2019-11-28T20:30:00Z' },
    { appointment_start: '2019-11-28T21:00:00Z' },
    { appointment_start: '2019-11-28T21:30:00Z' },
    { appointment_start: '2019-11-28T22:00:00Z' },
    { appointment_start: '2019-11-28T22:30:00Z' },
    { appointment_start: '2019-11-28T23:00:00Z' },
    { appointment_start: '2019-11-28T23:30:00Z' },
    { appointment_start: '2019-11-29T00:00:00Z' },
    { appointment_start: '2019-11-29T00:30:00Z' },
    { appointment_start: '2019-11-29T17:00:00Z' },
    { appointment_start: '2019-11-29T17:30:00Z' },
    { appointment_start: '2019-11-29T18:00:00Z' },
    { appointment_start: '2019-11-29T18:30:00Z' },
    { appointment_start: '2019-11-29T19:00:00Z' },
    { appointment_start: '2019-11-29T19:30:00Z' },
    { appointment_start: '2019-11-29T20:00:00Z' },
    { appointment_start: '2019-11-29T20:30:00Z' },
    { appointment_start: '2019-11-29T21:00:00Z' },
    { appointment_start: '2019-11-29T21:30:00Z' },
    { appointment_start: '2019-11-29T22:00:00Z' },
    { appointment_start: '2019-11-29T22:30:00Z' },
    { appointment_start: '2019-11-29T23:00:00Z' },
    { appointment_start: '2019-11-29T23:30:00Z' },
    { appointment_start: '2019-11-30T00:00:00Z' },
    { appointment_start: '2019-11-30T00:30:00Z' }
  ],
  total_entries: 32,
  links: {
    self: 'https://api.cliniko.com/v1/businesses/81977/practitioners/108233/appointment_types/394354/available_times?from=2019-11-28&to=2019-11-29&page=1&per_page=100'
  }
}
```

**Comment by JohnColvin** [comment]
Hi Craig,

That's a weird one. I'm not exactly sure why it's doing that. That business doesn't offer that appointment type, though. I think that might be causing some issue.

Let me know if that fixes it. If so, we'll have to look into what that endpoint is doing when given an appointment type that the business doesn't offer.

Best,
John

**Comment by mphalliday** [comment]
Hey @craigspaeth & @lionsdwarf 👋 

Just looking into this a bit further. It doesn't appear that practitioner has any unavailable blocks on the date ranges you are searching for. The screenshot above is showing unavailable blocks from Oct 28 thru Nov 1, yet the query you are using has a start date of Nov 28 to Nov 29. Can you confirm this on your end?

Cheers,
Michael

**Comment by craigspaeth** [comment]
@mphalliday @JohnColvin D'oh! 🤦‍♂

Thanks so much for your patience in helping us debug this. I think we've had our heads spinning after just expanding to multiple timezones and missed this obvious human error. Re-running it does seem to be correctly acknowledging unavailable blocks—but maybe this highlights an off-by-one month index vs. month date number error in our code.

I appreciate the help! 🙌

**Comment by mphalliday** [comment]
No worries!! Always happy to help! Glad we figured it out 🎉
