### ISSUE TITLE
Available times endpoint returning intervals based on the wrong appointment type 

### ISSUE THREAD

**Issue by craigspaeth** [redguava/cliniko-api#280]
The [available times](https://github.com/redguava/cliniko-api/blob/master/sections/available_times.md) endpoint seems to be picking the wrong time slot intervals abitrarily based on whichever appointment type was created first in the list.

Here's an example in our https://staging-octave.cliniko.com account where I have a practitioner only offering the pictured 30 min "Consult Interview - In Person" `394354`. As expected it returns 30-minute intervals. Later I add them to the 45 min "Mindfulness for Stress Management (Accept)" `319735` appointment type and it returns 45-minute intervals, even though I'm requesting the endpoint for the "Consult Interview - In Person" as you can see in the `links.self` path with `/appointment_types/394354`:

![cap](https://user-images.githubusercontent.com/555859/67718504-493afa00-f9a6-11e9-89e8-2b96ac054c62.gif)

**Comment by JohnColvin** [comment]
Hi Craig,

The practitioner's default appointment type is used to determine the size of the time slots. This is an assumption we make that most appointments will be of the default type. Organizing appointment slots based on the default leaves the best chance that a practitioner will not end up with unwanted gaps in their day. The endpoint uses the appointment type that you provide to decide where that type of appointment could fit in the practitioner's schedule.

There was a similar question from the google group a while back that has some more details and a concrete example: https://groups.google.com/a/redguava.com.au/forum/#!searchin/cliniko-api/available$20times%7Csort:relevance/cliniko-api/voDatAopca4/04Hh-u5_CQAJ

**Comment by craigspaeth** [comment]
@JohnColvin Ah ha! That clears things up. Thank you so much for your patience and help. Sorry to bother you with these questions we could have probably answered ourselves with more detective work.
