### ISSUE TITLE
Ability to update contact's doctor type

### ISSUE THREAD

**Issue by jahkey** [redguava/cliniko-api#287]
Hi,

I was trying to update doctor_type but was getting the following response
![Screenshot 2019-12-10 06 51 18](https://user-images.githubusercontent.com/1211611/70484689-9246a800-1b27-11ea-97c3-16b633a5a642.png)

**Comment by hagen** [comment]
Hi @jahkey,

I think you're looking for `type_code` 👍

```json
{
  "type": "Doctor",
  "type_code": 1
}
```

**Comment by jahkey** [comment]
Hi @hagen , changing the type_code does not change the doctor type
![Screenshot 2019-12-10 08 44 23](https://user-images.githubusercontent.com/1211611/70485285-78a66000-1b29-11ea-8754-b00d969f993a.png)

I would like to programmatically change the value of this new contact field
![Screenshot 2019-12-10 08 43 36](https://user-images.githubusercontent.com/1211611/70485293-7e9c4100-1b29-11ea-8e1a-68b5c83213cf.png)

**Comment by hagen** [comment]
Ah quite right! 
It’s relatively new and hasn’t made it into our public API yet.
Unless there’s a reason not to, I’ll raise a PR on our side to add that field. Either way, I’ll reply back here 😊

**Comment by jahkey** [comment]
@hagen Thank you very much. I appreciate your immediate response :)

**Comment by hagen** [comment]
@jahkey - the field is there; you just need to know what values it'll accept.
The string values: `general_practitioner` or `specialist`; or a `null` to clear its value.
I'll update our docs to reflect this.

**Comment by jahkey** [comment]
Awesome! Did it and it worked! Thank for the quick changes :)
