### ISSUE TITLE
Typo error: wrong key name in upload the file to our s3 bucket

### ISSUE THREAD

**Issue by prasadtelkikar** [redguava/cliniko-api#291]
A typo error in example given for uploading the file to our s3 bucket.

Section:
 - Upload the file to our s3 bucket 
      - Using signature version 4.
           - Current key value pair =  `-F 'x-amx-date=TIMESTAMP' \`
           - Correct key value pair =  `-F 'x-amz-date=TIMESTAMP' \`

**Comment by prasadtelkikar** [comment]
I fixed this issue and raised PR for the same #292

**Comment by bpinto** [comment]
Thank you @prasadtelkikar
