### ISSUE TITLE
Add MirrorAR as a custom patient button to Cliniko App

### ISSUE THREAD

**Issue by prasadtelkikar** [redguava/cliniko-api#293]
Hi Team,

We are integrating [MirrorAR ](https://app.mirrorar.io/)app with Cliniko, we want to add MirrorAR as a custom patient button in Cliniko app.
We are following [Custom Patient page](https://github.com/redguava/cliniko-api/blob/master/guides/custom_patient_page.md) documentation.

To do that, below are the endpoints to receive GET requests from browsers with Cliniko patient id as a query string parameter.

Integration endpoints:
Dev URL: https://test.mirrorar.io/cliniko/default/call/json/displayPatientProfile?patient_id=<Cliniko ID of displayed patient> 
Production URL: https://app.mirrorar.io/cliniko/default/call/json/displayPatientProfile?patient_id=<Cliniko ID of displayed patient> 

We request you to whitelist [https://*.mirrorar.io](https://*.mirrorar.io) to your list of approved applications.

**Comment by hagen** [comment]
@prasadtelkikar - we'll be adding this in for you. Before we do so, could you give us some background as to what MirrorAR does and how you integrate with Cliniko? Please send that to support@cliniko.com.

**Comment by nneufeld** [comment]
Hi @prasadtelkikar! We've added your endpoint to the whitelist, though just the production one(we haven't been adding dev endpoints for any integrations).

**Comment by prasadtelkikar** [comment]
Thanks  @nneufeld for adding our endpoint, now custom button is working as expected.
