### ISSUE TITLE
Medicare number shows up twice in import selection dropdown

### ISSUE THREAD

**Issue by anthony-hull** [redguava/cliniko-api#301]
![image](https://user-images.githubusercontent.com/47184118/83129581-e8f36e80-a0d4-11ea-9834-54689b5cb9e8.png)

**Comment by metabren** [comment]
The "Medicare reference number" is different from the "Medicare number". The "Medicare reference number" field is hidden on the patient record — possibly until it has a value, or perhaps until the "Medicare number" field is filled. I can't remember exactly. 😅

Note: I don't work for Cliniko, I've just come across this in the past.

**Comment by bart3k** [comment]
> The "Medicare reference number" is different from the "Medicare number"

Those are indeed different numbers (at least in Australia...). Medicare reference number is a field where you can store Medicare IRN - value on the left of the patient’s name on their Medicare card.
