### ISSUE TITLE
API URL for UK-based accounts

### ISSUE THREAD

**Issue by digime99** [redguava/cliniko-api#302]
Is there a different base URL for the API if the account we're trying to access is stored in the UK or Canada rather than Australia?

We're currently getting a 401 response using https://api.cliniko.com/v1 with a UK-based account

**Comment by hagen** [comment]
Hey @digime99 

there definitely is! This [guide on sharding](https://github.com/redguava/cliniko-api/blob/master/guides/sharding.md) will explain it all 👍
