### ISSUE TITLE
Populate referral source for patient

### ISSUE THREAD

**Issue by digime99** [redguava/cliniko-api#304]
Just wondering if there is any update on being able to populate "Referral source" for a patient via the API.

My understanding is that whatever we pass in patient.referral_source will populate "Extra Information", and the referral source will always be "Other".

This article seems to imply that it's possible to populate a manually-added referral source against a patient... http://help.finger-ink.com/en/articles/3701041-why-aren-t-referral-sources-populating-the-patient-record-correctly

**Comment by metabren** [comment]
Hey @digime99. As per our article, this is indeed possible. Here's the relevant documentation: https://github.com/redguava/cliniko-api/blob/master/sections/referral_sources.md
