### ISSUE TITLE
Deleted Treatment Notes API endpoint error updated_at is not filterable

### ISSUE THREAD

**Issue by jahkey** [redguava/cliniko-api#305]
According to the documentation, treatment notes can be filtered by updated_at https://github.com/redguava/cliniko-api/blob/master/sections/treatment_notes.md 

Getting the following error:
response: {
    status: 400,
    statusText: 'Bad Request',
    headers: {
      ...
    },
    config: {
      url: 'https://api.cliniko.com/v1/treatment_notes/deleted',
      method: 'get',
      params: [Object],
      headers: [Object],
      auth: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus],
      data: undefined
    },
    request: <ref *1> ClientRequest {
      ... 
      _header: 'GET /v1/treatment_notes/deleted?per_page=100&page=1&q=updated_at:%3E2020-06-18T02:16:31.000Z HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'User-Agent: XXXXXX' +
        'Host: api.cliniko.com\r\n' +
        'Authorization: Basic XXXXXXXX=\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      path: '/v1/treatment_notes/deleted?per_page=100&page=1&q=updated_at:%3E2020-06-18T02:16:31.000Z',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { message: 'updated_at is not filterable' }

**Comment by hagen** [comment]
Hi @jahkey 
deleted resources are only filterable by `deleted_at` - on the basis that they will never again be updated.
Please try your query again, replacing the query filter with `deleted_at` instead of `updated_at` 😊

We'll update the docs to make that clear.

Cheers!

**Comment by jahkey** [comment]
Thanks! :)
