### ISSUE TITLE
Filter contacts by name

### ISSUE THREAD

**Issue by digime99** [redguava/cliniko-api#307]
Any chance you can add first_name, last_name filters for contacts? We're wanting to offer a typeahead on a form to lookup a referring doctor/specialist (so we can then set referral_source.referrer_id)

**Comment by bpinto** [comment]
For sure, we'll be adding them shortly. I'll let you know when it happens 👍

**Comment by bpinto** [comment]
@digime99 filter by contact name (first and last) has been added.
