### ISSUE TITLE
Expose patient.accepted_email_marketing

### ISSUE THREAD

**Issue by digime99** [redguava/cliniko-api#309]
Just wondering if you're able to expose accepted_email_marketing against a patient - we're only able to access accepted_sms_marketing at the moment, but there are checkboxes for both in the GUI.

**Comment by metabren** [comment]
Hey @digime99 — AFAIK it's already there (try it out on a test patient yourself). Just not documented yet.

**Comment by digime99** [comment]
yes you're right, thanks!
