### ISSUE TITLE
403 with PUT Request

### ISSUE THREAD

**Issue by stuartcottrell** [redguava/cliniko-api#311]
We're having an issue making a PUT request.

We have ensured we are implementing the correct headers in Postman and we can actually make a GET request with the same details but when we come to make the PUT request we get a 403.

**Request Headers**

Accept: application/json
User-Agent: xxxxxx (xxxxxx@xx.xxx)
Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Content-Type: application/json
Postman-Token: fc14e179-83fb-4920-b099-23ab6c0f698a
Host: api.uk1.cliniko.com
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 1404

**Request Body**

{
    "content": {
        "sections": [
            {
                "name": "PCR Result Information",
                "questions": [
                    {
                        "name": "Date of Test",
                        "type": "text",
                        "answer": "26/07/20"
                    },
                    {
                        "name": "Date of Result",
                        "type": "text",
                        "answer": "26/07/20"
                    },
                    {
                        "name": "Result",
                        "type": "radiobuttons",
                        "answers": [
                            {
                                "value": "SARS-CoV-2 NOT Detected",
                                "selected": true
                            },
                            {
                                "value": "SARS-CoV-2 Detected"
                            }
                        ]
                    },
                    {
                        "name": "Sent",
                        "type": "checkboxes",
                        "answers": [
                            {
                                "value": "Yes"
                            }
                        ]
                    }
                ]
            }
        ]
    }
}

We are trying to put a "selected": true underneath the "value": "Yes" so that the checkbox becomes checked.

Any ideas guys?

**Comment by JohnColvin** [comment]
see thread on the google group https://groups.google.com/u/1/a/redguava.com.au/g/cliniko-api/c/_SEYNCEBnp8/m/ovx_xI7GAAAJ
