### ISSUE TITLE
Request: Patient Cases and Health Fund Claim Endpoints

### ISSUE THREAD

**Issue by fergusmac** [redguava/cliniko-api#312]
Hi,

Pretty straightforward - I'd love if there was an endpoint for Patient Cases, and for Health Fund Claims.

Patient Cases is useful to e.g. send an email to client or practitioner when a case is finished (which may require them to take some action).

Health Fund Claims is useful to check for invoices where a claim should've been made but was missed due to user error.

Thank you

**Comment by hagen** [comment]
Hi @fergusmac ,

there's a discussion on this over at our Google Group: https://groups.google.com/a/redguava.com.au/forum/#!topic/cliniko-api/dYm6uFgLqqs

We don't have an ETA for Patient Cases in the API, but it's something we're planning to add. We don't have any plans to add Health Fund Claims.
