### ISSUE TITLE
Archived patients and medical alerts

### ISSUE THREAD

**Issue by nicholasmott** [redguava/cliniko-api#318]
Hi Team Cliniko,

We are adding Medical alert syncing to Instinctive Notes and I've come up with a response I didn't expect.

If you call the patients endpoint it doesn't include archived patients, as expected, as those patients are in the patients/archived endpoint.

If you call the medical alerts endpoint you get all medical alerts, including from archived patients.

We generally use the archived patients list to tell us when a current patient is set to archived. We don't add archived patients that existed before a customer signed up to Instinctive Notes as they will never have appointments while archived and there's no need for us to have that data.

This means that the first time we call the medical alerts endpoint for any customer there will be a set of results returned which will never match as the patient will never exist in Instinctive Notes. We would usually use a missing patient as a prompt to go a get their record, eg in case an appointment came in before a patient was loaded, but trying to do this with an archived client results in a 404.

So the question is, if a patient is set to archived, should their records also be archived and not provided through the API. Or could a filter be added to transactional items (appointments, medical alerts, etc) which would allow excluding records if they were from an archived patient.

Let me know if you think either of these approaches is worth considering (or if there is another better answer). At the end of the day we can manage the issue on our side if necessary by throwing away records where a patient never arrives, but if you thought it would be valuable to do something here we would find it useful.

Cheers,
Nick

**Comment by bpinto** [comment]
Hi @nicholasmott,

sorry for taking this long to answer. Unfortunately, we don't have a plan or solution for this yet. We have only had a few talks about this yet and this is something that will require deeper thoughts to make sure we get this right.
