### ISSUE TITLE
Deleted medical alert not listed

### ISSUE THREAD

**Issue by nicholasmott** [redguava/cliniko-api#319]
Hi Team Cliniko,

I'm testing medical alert deletions through the API and it's not returning the alerts I'm deleting.

Two alerts I have deleted are not showing when getting all deleted records for my test account
- 2163523
- 3113003

I am calling: curl "https://api.au1.cliniko.com/v1/medical_alerts/deleted" -u API_KEY: -H 'Accept: application/json' -H 'InstinctiveNotes (support@instinctivenotes.com)'

Three records are returned but they are all very old.

Is there some kind of delay between deleting an alert in Cliniko and having it appear in the API?

Thanks,
Nick

**Comment by JohnColvin** [comment]
Hey Nick,

Medical alerts have a distinction between archived and deleted. Since they
belong to patients which can be permanently hard deleted, they can also be
permanently hard deleted. (This started with GDPR compliance). What you've
done is archived (soft deleted) those medical alerts and they can be found
on the medical_alerts/archived route. Archived medical alerts still have
their content, deleted medical alerts only retain their ID and when they
were deleted.

Best,
John

**Comment by nicholasmott** [comment]
Hi John,

Thanks for the detail, makes sense.

The medical alerts section of the documentation doesn't have medical_alerts/archived - hence the question.

I assume the only way to have a medical alert actually deleted is to hard delete the Patient, as after you archive an alert it disappears and there appears to be no way to hard delete an individual note.

I've checked the archived endpoint and I notice that each record has an archived_at field and a deleted_at field and they are both filled with the same date/time. Is this expected behaviour or should the deleted_at be nil until the medical alert is hard deleted?

Thanks,
Nick

**Comment by bpinto** [comment]
> I've checked the archived endpoint and I notice that each record has an archived_at field and a deleted_at field and they are both filled with the same date/time. Is this expected behaviour or should the deleted_at be nil until the medical alert is hard deleted?

They are aliased attributes, our goal is to always expose them as `archived_at` but since we need to maintain backwards compatibility, for end points where the `deleted_at` attribute was already exposed, we will have the same information available with two different names.
