### ISSUE TITLE
Add treatment note endpoints

### ISSUE THREAD

**Issue by nicholasmott** [redguava/cliniko-api#32]
Hi Chaps,

We'd like to access historical treatment notes for patients and also be able to push new treatment notes back to Cliniko.

Given the flexibility of Cliniko treatment notes this could be a little tricky so happy to discuss further if useful.

Cheers,
Nick

**Comment by stephenandrews** [comment]
We'd like to see this as well - any ETA guys?

**Comment by JohnColvin** [comment]
Sorry, no ETA for this. We're focusing on other parts of the app, but we do know that people want this very much.

**Comment by nicholasmott** [comment]
Hey Chaps. Just thought I'd request an update on this. Currently more that 50% of our prospects and trial customers ask to be able to send notes back to Cliniko.

Any chance you could bump this up the priority list. Even if we were able to just send some text into what ever standard treatment template you have would go a long way to making current and potential customers happy.

**Comment by longboard3r** [comment]
Hi Red Guava devs, my client needs to have patients complete a pre-appointment form. Ideally this would be a user configurable part of the Cliniko app. 

If not possible, how about simply providing a way to make a custom URL with Cliniko patient ID in the appointment confirmation emails? At least then Cliniko customers can use the patient ID to send pre-appointment data to the patient notes field via the API. 

Thanks

**Comment by waynebritton** [comment]
I've a client that really needs a way to update treatment notes and add attachments. Any news if the API will soon support this?

**Comment by JohnColvin** [comment]
Sorry folks, no news yet on treatment notes or attachments. We're working on some changes to how we store treatment note data, once that's in place it will be easier for us to expose it via API.

**Comment by metabren** [comment]
Hi @JohnColvin any update on this at all? We'd love to be able to do this via [Finger-Ink](https://finger-ink.com/add-ons/cliniko).

**Comment by JohnColvin** [comment]
No concrete news. The effort I mentioned in the comment above from July stalled out in favor of other work.

It's serendipitous that you've asked today, though. I'm turning my attention back to this as of today, after completing some other work. Reworking the structure of treatment notes and making them accessible via API is something we're doing as part of the new body charts feature. We'd like to release that ASAP, but as always we'll take the time we need to get it right before we do

I'm not sure yet what that will mean for releasing them to third party API. We typically get new endpoints in place and use them internally for a while to vet them, but rest assured work is being done in this area again.

**Comment by metabren** [comment]
Thanks for the update. If [we](https://github.com/Finger-Ink) can do anything to help (testing etc.) please let us know. We're very keen to get see this working, along with [attachments](https://github.com/redguava/cliniko-api/issues/34). In fact, attachments is probably more of a priority for us as it allows us to send through signed PDF consent forms.

**Comment by ducas** [comment]
👍 this is a deciding feature for our platform that is in the design phase right now so I would love to hear any updates.

**Comment by Taylorsuk** [comment]
+1
This is essential for our App to be fully integrated - one of the biggest requests from our users is to be able to add the exercise prescription to the patients notes.

**Comment by andrewgoodnz** [comment]
Any further update on this? In the process of migrating patient notes and this is going to be a massive barrier :(

**Comment by bpinto** [comment]
Hi @andrewgoodnz it's an ongoing feature but it's not ready yet. We need this API to release other features inside Cliniko so this is going to happen sooner than later.

**Comment by nicholasmott** [comment]
Always nice to get rid of an old issue - thanks for all your work on the API, it really is awesome!

**Comment by mjames86** [comment]
Is it ready yet?

**Comment by metabren** [comment]
@mjames86 this has been live for a while now, check out:

- https://github.com/redguava/cliniko-api/blob/master/sections/treatment_notes.md
- https://github.com/redguava/cliniko-api/blob/master/sections/treatment_note_templates.md
