### ISSUE TITLE
Are Custom Patient Forms Available by API?

### ISSUE THREAD

**Issue by phil-lgr** [redguava/cliniko-api#323]
https://help.cliniko.com/en/articles/3945156-getting-started-with-secure-patient-forms

I'd like to know if it's possible to access the form templates, also submit entries from the API.

Thank you!

**Comment by JohnColvin** [comment]
Hi Phil,

Forms aren't available on yet. This is in progress, though.

Best,
John

**Comment by phil-lgr** [comment]
Hi @JohnColvin any update on this? do we have a way to retrieve forms info at this point?

**Comment by JohnColvin** [comment]
Hi Phil,

One of the devs is currently working on this. There was some new
functionality we needed to handle for it. Hopefully it'll be rolling out
soon, as long as we don't uncover any other issues.

Best,
John

**Comment by phil-lgr** [comment]
@JohnColvin thank you for your reply

if we can be of any assistance to test early versions let us know

**Comment by phil-lgr** [comment]
@JohnColvin at this point what are our options to know if a patient has forms or not?

I think I will have to use puppeteer to crawl the UI if we can't access the info by API :/

**Comment by bpinto** [comment]
@phil-lgr Sorry it's taking longer than you expected, but this feature has requested a few changes we had to do prior to releasing it. We might release it tomorrow, it's that close.

**Comment by phil-lgr** [comment]
@bpinto, no prob, let us know — in the meantime, we can prob find workarounds with Treatment Notes that are available through the API

**Comment by bpinto** [comment]
@phil-lgr we are working on the docs, it should probably be announced in the next couple hours.

**Comment by nneufeld** [comment]
Hi @phil-lgr, it's been released, the docs are mostly ready, and you can take an early look at them [here](https://github.com/redguava/cliniko-api/tree/patient-forms-api).

Please let us know if you have any issues or questions!

**Comment by phil-lgr** [comment]
@nneufeld thanks for the update! I'm just having a look right now !

**Comment by phil-lgr** [comment]
@nneufeld @bpinto is there a way to follow the forms associated with a patient ?

e.g.

```json
"forms": {
    "links": {
      "self": "https://api.ca1.cliniko.com/v1/patients/563704455636192073/forms"
    }
  },
```

**Comment by JohnColvin** [comment]
Hey Phil,

We don't have the link from patient to forms on the patient response right
now. We should, but it got missed in the roll out.

That patient forms endpoint does accept a patient_id filter, so you can
achieve this by doing this:

/v1/patient_forms.json?q=patient_id:=372481449527346255

Best,
John
