### ISSUE TITLE
Add medical alerts to patient end points

### ISSUE THREAD

**Issue by nicholasmott** [redguava/cliniko-api#33]
It would be useful to be bi-directional so that they come down with a get patient and they can also be updated back to Cliniko.

**Comment by bpinto** [comment]
Hi @nicholasmott,

we have just added end points for medical alerts, documentation can be found on https://github.com/redguava/cliniko-api/blob/master/sections/medical_alerts.md and https://github.com/redguava/cliniko-api/blob/master/sections/patients.md.

Thanks for the request.

**Comment by nicholasmott** [comment]
Great. Thanks @bpinto. Will be adding these in the next set of updates we do.
