### ISSUE TITLE
Add end point for patient attachments

### ISSUE THREAD

**Issue by nicholasmott** [redguava/cliniko-api#34]
Provide an endpoint for downloading and uploading patient attachments.

**Comment by Jassop** [comment]
This would be a feature I would be interested in too. We have a simple form on our website for clients to add their own details (thanks for the API!) and it would be great if we could attach the Health Questionnaire we get them to complete at the same time. 

Thanks

**Comment by theprogramme** [comment]
Hi,

We're keen to see attachment read/write endpoints too. Specifically, we'd like to deliver referral letters from GP clinical software to Cliniko at the time an appointment booking is made. The letter would then be associated with the patient record. After the consult(s) we'd like to have a way to deliver a report back to the referring GP.

Cheers,
Christian

**Comment by rojotek** [comment]
I'm looking at integrating with cliniko at the moment to push up a background questionnaire and some initial assessment documents for therapists. Attachments would be one of the key things I'd like to share.

**Comment by rojotek** [comment]
Are there any updates on whether this API endpoint is being thought about at all?

**Comment by JohnColvin** [comment]
Nothing yet. It's on our list, just not at the top.

**Comment by JRosanowski** [comment]
Another use for this would be adding pictures of moles, verrucas, and fungal nails etc straight from a phone.

**Comment by sauronnikko** [comment]
I also would like this endpoint to be made. It would be very useful

**Comment by JohnColvin** [comment]
I'm happy to report that this is finally done.

https://github.com/redguava/cliniko-api/blob/master/guides/uploading_patient_attachments.md
https://github.com/redguava/cliniko-api/blob/master/sections/patient_attachments.md
