### ISSUE TITLE
403 Error when posting patient attachments

### ISSUE THREAD

**Issue by rclarke1** [redguava/cliniko-api#341]
The last 2 days I have started getting 403 errors when putting POST requests to the patient attachments endpoint. Has anything changed in this process? I have been successfully doing this for the last year or so.
Thanks
Richard

**Comment by JohnColvin** [comment]
Hi Richard,

We recently deprecated the old way of uploading patient attachments as
announced in this post:
https://groups.google.com/u/1/a/redguava.com.au/g/cliniko-api/c/SmmLizHXfDQ/m/YnrFiCSaAQAJ

You're probably still using v2 signing and need to update to handle v4
instead.

Best,
John

**Comment by rclarke1** [comment]
Thanks,
Yes updating according to v4 worked. I would have got the initial mailing list announcement but not followed up on it.
