### ISSUE TITLE
VoIP Phone integration

### ISSUE THREAD

**Issue by cfonevoip** [redguava/cliniko-api#343]
Hello everyone,

How do I query the cliniko api for a patient name, when I have their phone number?

**Comment by mebezac** [comment]
Unfortunately, there is currently there is no way to filter patients by a phone number: https://github.com/redguava/cliniko-api/blob/master/sections/patients.md#filtering-patients

**Comment by cfonevoip** [comment]
The scenario is 
I have cliniko + a cloud phone system
I have an incoming phone call. 
I control the phone system (it's cloud based)
I want to send the phone number to the cliniko API and get a return of the patients name
How do I query the API for a patient name?

**Comment by mebezac** [comment]
The process you describe unfortunately can not be done. There isn't a way to "send the phone number to the cliniko API and get a return of the patients name"

**Comment by mebezac** [comment]
I should mention however, there is a section of our Community where you request that a new feature like this be added: https://community.cliniko.com/c/feature-requests/5
