### ISSUE TITLE
invalid/invalid content type for patient attachment

### ISSUE THREAD

**Issue by m3alamin** [redguava/cliniko-api#348]
I'm trying to attach a file to a patient using the following endpoint:

`/v1/patient_attachments`

Seems everything is fine but I am getting `"content_type": "invalid/invalid"`

I am trying to attach a pdf file with the path: @/home/.../public_html/.../storage/uploads/sample.pdf

**Comment by hagen** [comment]
Hi there,
I think you asked this in our Google Group too. Have answered over there.

Cheers
