### ISSUE TITLE
Very large Patient ids?

### ISSUE THREAD

**Issue by JRosanowski** [redguava/cliniko-api#360]
Are Patient ids supposed to be integers? I've just hit some that are very big numbers. This is on the au1 shard.

This is the last one in the list before they get crazy big.
> {
>       "id": "75335355",
>       "created_at": "2022-02-25T01:28:28Z",
>       "updated_at": "2022-02-25T01:28:28Z",
>       "accepted_email_marketing": false,
>       "accepted_privacy_policy": null,
>       "accepted_sms_marketing": true,

> {
>       "id": "836447129235883061",
>       "created_at": "2022-02-28T01:51:08Z",
>       "updated_at": "2022-03-04T00:02:38Z",
>       "accepted_email_marketing": false,
>       "accepted_privacy_policy": null,
>       "accepted_sms_marketing": true,

> {
>       "id": "837047015488620153",
>       "created_at": "2022-02-28T21:43:00Z",
>       "updated_at": "2022-02-28T21:43:00Z",
>       "accepted_email_marketing": false,
>       "accepted_privacy_policy": null,
>       "accepted_sms_marketing": true,

snip...

> {
>       "id": "839282071800120868",
>       "created_at": "2022-03-03T23:43:39Z",
>       "updated_at": "2022-03-03T23:43:39Z",
>       "accepted_email_marketing": false,
>       "accepted_privacy_policy": null,
>       "accepted_sms_marketing": true,

Thanks,
Jon

**Comment by bpinto** [comment]
Those are 64 bits integer. Given not all languages support integer this large the API will send the ID as strings even though this field will only contain numeric characters.

All shards but the au1 shard were already creating records that had such big numbers as their ID but starting this last weekend we have upgraded au1 shard to do the same.

**Comment by JohnColvin** [comment]
@JRosanowski You should join our API google group https://groups.google.com/a/redguava.com.au/g/cliniko-api/c/-zgcbADWOKQ

That's where we post important announcements. You can see the recent thread about this here: https://groups.google.com/a/redguava.com.au/g/cliniko-api/c/-zgcbADWOKQ

**Comment by JRosanowski** [comment]
Thanks for the info!
