### ISSUE TITLE
Get practitioners by appointment type (and vice versa)

### ISSUE THREAD

**Issue by Michae1Wan** [redguava/cliniko-api#37]
Hi there, This is Michael from AppsWiz. Just wondering if your system can have the ability to search all practitioners that do a certain appointment type (Physiotherapy, for example), as well as the appointment types provided by a practitioner. So basically search practitioners by a appointment type or search appointment types by the practitioner. The current data returned by the web service does not have enough info to do this client-side.

Regards

Michae1

**Comment by Michae1Wan** [comment]
Hi John,

Sorry for the late response. The use case is for search filtering - so that when a user chose an appointment type I can fetch the practitioners that do this particular appointment (and vice versa).

**Comment by JohnColvin** [comment]
These endpoints are now available. You can get a practitioner's appointment types: `/practitioners/123/appointment_types` and the practitioners that offer an appointment type: `/appointment_types/456/practitioners`
