### ISSUE TITLE
Bookings API appointment type filter not working

### ISSUE THREAD

**Issue by briandestura** [redguava/cliniko-api#376]
Hello!

The Bookings API doc says that appointment type id is filterable:
https://docs.api.cliniko.com/openapi/reference/tag/Booking/#tag/Booking/operation/ListBookings-Get

But hitting this API:
```
https://api.au1.cliniko.com/v1/bookings?q[]=appointment_type_id:=1039424726251865516
```
Gives back a 400 with response:
```
{
    "message": "appointment_type_id is not filterable"
}
```
Are the docs updated or is this a planned future release?

**Comment by loumarven** [comment]
Hi Brian,

The bookings endpoint should now be filterable by appointment_type_id.
Thanks!
