### ISSUE TITLE
Add extra info to appointment types

### ISSUE THREAD

**Issue by lcannon** [redguava/cliniko-api#44]
It would be great to be able to get information on prices, if shared, and also to know which appointment type is set as the default one.

Thanks.

**Comment by benwhyte** [comment]
Is it possible to add the Description field to the data returned in the appointment_types endpoint?

**Comment by JohnColvin** [comment]
@benwhyte We've add the description field.

**Comment by benwhyte** [comment]
Thanks for the quick turnaround time!
