### ISSUE TITLE
API Patients and New Request

### ISSUE THREAD

**Issue by Andrewche55** [redguava/cliniko-api#54]
Could you please add in the Patients section properties for Reference Number, Invoice To, Invoice To Email, Invoice Extra Info?

On that can I also request a Contacts section so you can implement Referring Doctor to the Patients section.

Thank you.

**Comment by jfriedlaender** [comment]
Andrew, we're going to release the extra patient fields you want shortly.  If you still need the contacts/referring doctor in the API, could you please raise a separate issue for that.

Thanks!
