### ISSUE TITLE
Get Patient(s) extra information

### ISSUE THREAD

**Issue by damonmcminn** [redguava/cliniko-api#60]
Is it possible to include for each patient, a link to their next and previous appointment (if exists)?

**Comment by jfriedlaender** [comment]
Just an update, we're planning on releasing custom sorting soon, so you'll be able to choose a field and which direction to sort in.  Combine that with our new options to filter and you can achieve this easily.  I'll update when sorting is live.

**Comment by JohnColvin** [comment]
We've released custom sorting. You can get a patients next appointment like this now:
`api.cliniko.com/v1/patients/123/appointments?q=appointment_start:>2015-03-29T15:05:22Z&sort=appointment_start&per_page=1`

**Comment by damonmcminn** [comment]
Brilliant, thanks!
