### ISSUE TITLE
Push exercises into Cliniko

### ISSUE THREAD

**Issue by KproApps2** [redguava/cliniko-api#61]
Can you confirm that It is not possible for exercises to be exported to Cliniko? Is it only patient information that is possible?

**Comment by derrix060** [comment]
This issue could be closed, what do you think?

**Comment by JohnColvin** [comment]
I think you're right. This can probably be done with the treatment notes API now. https://github.com/redguava/cliniko-api/blob/master/sections/treatment_notes.md
