### ISSUE TITLE
Request: Add a way to determine which practitioners work at a business.

### ISSUE THREAD

**Issue by nathanblogs** [redguava/cliniko-api#62]
Hi,

Currently we have no way of finding which practitioners work at which business.

This means we loop through every business and then loop through every practitioner to see if they have available times which causes unneeded requests which return 404.

Regards

Nathan

**Comment by JohnColvin** [comment]
Hi Nathan,

I'm happy to report that we've just added an endpoint for this!

Businesses now return a `practitioners` key that has a link to the endpoint that lists the practitioners for that business. We've updated the docs with info on how to get this data:
https://github.com/redguava/cliniko-api/blob/master/sections/practitioners.md#get-practitioners
https://github.com/redguava/cliniko-api/blob/master/sections/businesses.md#get-businesses

Thanks for using the Cliniko API!

Cheers,
John
