### ISSUE TITLE
Available appointment times incorrect when restricting number of bookings

### ISSUE THREAD

**Issue by RyanPaddy** [redguava/cliniko-api#64]
Hi folks, I have an issue with available appointment times in the API. When restricting number of appointments to show, the wrong start times are shown.  

For example, we have a practitioner with appointments of 45 minutes duration. 

If we restrict online bookings to show 2 appointments in the afternoon, and that practitioner is available from 12:15pm to 2:30pm and 4pm to 6:15pm, the system shows available appointments at 12:15pm and 5pm. 

It should show 4pm, 4:45pm or 5:30pm. It works correctly if I allow all appointments to show as available, but not if I restrict number of appointments to show. 

Showing 5pm as an available time is not efficient, it means only 2 sessions of 45min length can be fitted into the 4pm to 6:15pm slot instead of 3. We're having to manually fix these bookings.  

It seems like the calculation of available start times needs to be changed to take account of available appointments that aren't being displayed due to the restriction.

**Comment by hagen** [comment]
Closing due to age. Please reopen if required.
