### ISSUE TITLE
Documentation appears incorrect - appointments

### ISSUE THREAD

**Issue by Klefen** [redguava/cliniko-api#69]
Hi just a small one, but annoyed me for a few hours.

the Create Appointment documentation shows sending the curl data through as a url type string, when in fact the api is actually expecting json much like the create patient.

Also, something a little wierd, and possibly an oversight, why must we pass in the end time of an appointment AND and appointment type. The appointment type contains the duration of the appointment thus an appointment end time could be calculated could it not?

Ta

DK

**Comment by jfriedlaender** [comment]
Hi DK,

I'm sorry we wasted your time with that. We really want to make our API a joy to work with, and those kind of things can be very frustrating.

I appreciate you letting us know and we'll gt the docs fixed an update this issue once done.

I'll leave your other question for one of our other devs to comment on.

Cheers,

Joel

**Comment by bpinto** [comment]
Hey @Klefen,

thanks for raising the documentation failure, it is fixed now.

We are discussing if there is a reason we can't add the logic to calculate the appointment end time based on the appointment type duration to our API. But I believe we will do it.

I'll let you know once I know more.

**Comment by bpinto** [comment]
We have done the changes and it's now live, appointment_end is not optional.

https://github.com/redguava/cliniko-api/commit/d79e0fcccd5036e95cf25d92d206161696f2c241

**Comment by JohnColvin** [comment]
@bpinto I think you mean appointment_end is _now_ optional. :smile:

**Comment by Klefen** [comment]
lol thanks John.

DK
ᐧ

**Comment by bpinto** [comment]
lol, small but significant typo. :P

Fixed on comment above.
