### ISSUE TITLE
Full patient referral source information not available. 

### ISSUE THREAD

**Issue by TM818** [redguava/cliniko-api#71]
Currently, it appears the only data returned by the API for a patient's referral_source field is the information in the referral source "Extra information" GUI field. 

Are we missing something or is this correct? If so, can you please alter this so it returns the full referral source information, or give us an ETA as to when that functionality might be added?

Thank you.

**Comment by JohnColvin** [comment]
Hey @VicVol,

You are correct. Previously, referrals were only the "extra information" field. We updated referrals a while back to be more structured, but the API hasn't been updated.

Thanks for bringing this to our attention, but I'm not sure when we'll get the full information in the API.
