### ISSUE TITLE
"504 Gateway Time-out" errors becoming more and more frequent. 

### ISSUE THREAD

**Issue by TM818** [redguava/cliniko-api#72]
According to past posts, you do not implement rate-limiting. Our application has a throttling engine built in, and we have been forced to throttle Cliniko API interaction more and more over the past few weeks. We do not see this with APIs for other products that we interact with, only Cliniko. We're literally up to pausing 2 full seconds every 10 Cliniko API interactions and it we still get random "504 Gateway time-outs" and "502 Bad Gateway (server returned incomplete response)" errors from Cliniko. It's getting to where our Cliniko products are becoming unreliable through no fault of our own. 

What are your thoughts on this?  Thank you for your time.

**Comment by geekle** [comment]
How often are you sending these requests and how often do you see these 5xx errors?

**Comment by TM818** [comment]
The answer varies for both of these questions, we simply noticed their frequency has been increasing as of late and know that there have not been dramatic infrastructure changes on our end. After bringing our throttling settings down to pausing for a full second every 5 Cliniko API calls, they seem to have subsided for now. Please note that this setting is dramatically more aggressive than the throttling settings we are required to use to meet the rate-limiting requirements of other API providers.

Closing ticket for now, just wanted to make your team aware. Thank you for your time.
