### ISSUE TITLE
patient_phone_numbers field on patient create suddenly no longer working (important, please advise).

### ISSUE THREAD

**Issue by VicVol** [redguava/cliniko-api#73]
We have a live app that utilizes Cliniko via the API that is suddenly no longer working for the following reason (please advise when possible): 

When we attempt to create a patient via the API, it works, with the exception of the patient_phone_numbers field, which has worked properly for months but now returns a HTTP 4XX/5XX error code no matter how we format it. We've tried every variation we can think of. We've made no changes to our code and received no notification of maintenance from Cliniko; were changes made in the way phone numbers are input, and if so, what were they? 

Example of code that was working properly until recently (we have tried many variations of this, as well as variations via curl):

    clph1ty = "Mobile"; clph1num = "8181112222"; clph2ty = "Work"; clph2num = "8182223333"; 
    RestClient.post("https://OUR_API_KEY@CLINIKO_PATIENT_URL",
        :first_name => @clfn, :last_name => @clfn, :email => @clem,
        :patient_phone_numbers => [
          {
            :phone_type => clph1ty,
            :number => clph1num
          },
          {
            :phone_type => clph2ty,
            :number => clph2num
          }
        ].to_json
    ) 

Example of curl attempt: 

curl https://api.cliniko.com/v1/patients \
  -u OUR_API_KEY: \
  -H 'Content-Type: application/json' \
  -H 'Accept: application/json' \
  -H 'User-Agent: APP_VENDOR_NAME (APP_VENDOR_EMAIL)' \
  -d '{ "first_name": "John", "last_name": "Snow", “patient_phone_numbers”: [ { “phone_type”: “Mobile”, “number”: “6155551212” } ] }' \ 
  -X POST

**Comment by mphalliday** [comment]
Hi @VicVol 

We did release a bug fix last week ... we were having issues when people actually posted well formatted json phone numbers to the API.  In your example above, the curl command should work, i just tried it locally ... had to remove the smart quotes though.

In your ruby code, I believe if you remove the `.to_json` call on your array, it should fix your problems:

````
clph1ty = "Mobile"; clph1num = "8181112222"; clph2ty = "Work"; clph2num = "8182223333"; 
RestClient.post("https://OUR_API_KEY@CLINIKO_PATIENT_URL",
    :first_name => @clfn, :last_name => @clfn, :email => @clem,
    :patient_phone_numbers => [
      {
        :phone_type => clph1ty,
        :number => clph1num
      },
      {
        :phone_type => clph2ty,
        :number => clph2num
      }
    ]
) 
```` 
Also, do make sure you're setting the `Accept` and `Content-Type` headers to `application/json`

Give that a try and let us know if it worked.  Also, be sure to subscribe to our cliniko-api google group, details of the bug fix were posted there:  https://groups.google.com/a/redguava.com.au/forum/#!topic/cliniko-api/n-M98ITF3XY

As a bounus, you are now able to delete phone number via the API by passing an empty array:
`patient_phone_numbers: []`

**Comment by VicVol** [comment]
Thank you for the prompt response. Unfortunately, we had tried removing the .to_json and just attempted again; we received the following result (if we eliminate the phone number field patient create works fine):

te - REQUEST: #<RestClient::Request:0x0000000280f230> --- RESPONSE: <?xml version="1.0" encoding="UTF-8"?>
<hash>
  <status>500</status>
  <error>Internal Server Error</error>
</hash>

Our updated code: 

                 else # f pait_first_name.empty? || pait_last_name.empty? || pait_email.empty?
                    testvar1 = "Mobile"; testvar2 = "8185551212"; testvar3 = "Work"; testvar4 = "8181112222"
                    RestClient.post("https://OUR_API_KEY@CLINIKO_PATIENT_URL",
                      :first_name => "Test",
                      :last_name => "Test",
                      :patient_phone_numbers => [
                        {
                          :phone_type => testvar1,
                          :number => testvar2
                        },
                        {
                          :phone_type => testvar3,
                          :number => testvar4
                        }
                      ]
                 )

**Comment by mphalliday** [comment]
Are you setting the `content-type` and `accept` headers to `application/json` in the RestClient?

**Comment by mphalliday** [comment]
So like this:

````
RestClient.post("https://OUR_API_KEY@CLINIKO_PATIENT_URL",{
                  :first_name => "Test",
                  :last_name => "Test",
                  :patient_phone_numbers => [
                    {
                      :phone_type => testvar1,
                      :number => testvar2
                    },
                    {
                      :phone_type => testvar3,
                      :number => testvar4
                    }
                  ]}, :content_type => :json, :accept => :json)

**Comment by VicVol** [comment]
Still receiving a 500 error from your servers:

RestClient::InternalServerError
Exception message:
500 Internal Server Error

Eliminated the variables and tried a variety of RestClient header settings. Current code:

                    response = RestClient.post("https://OUR_API_KEY@CLINIKO_PATIENT_URL", {
                      :first_name => "Test",
                      :last_name => "Test",
                      :patient_phone_numbers => [
                        {
                           :phone_type => "Mobile",
                           :number => "8181112222"
                        },
                        {
                           :phone_type => "Work",
                           :number => "8181234567"
                        }
                       ]}, :content_type => :json, :accept => :json) 

For the headers field, tried setting :content_type and :accept to 'application/json', tried breaking out those settings and putting them in a hash, then passing the hash as the headers parameter, etc. Any thoughts?

**Comment by mphalliday** [comment]
Okay, looks like with RestClient you need to call `.to_json` on the entire hash.  So give this a shot:

````
response = RestClient.post("https://OUR_API_KEY@CLINIKO_PATIENT_URL", {
                  :first_name => "Test",
                  :last_name => "Test",
                  :patient_phone_numbers => [
                    {
                       :phone_type => "Mobile",
                       :number => "8181112222"
                    },
                    {
                       :phone_type => "Work",
                       :number => "8181234567"
                    }
                   ]}.to_json, :content_type => :json, :accept => :json) 
````

**Comment by VicVol** [comment]
That did the trick, thank you. Interesting that you now have to encompass the entire RestClient parameter field in .to_json instead of just the :patient_phone_numbers element. Are there any other Cliniko API changes we should be aware of? 

Thank you again for your time.

**Comment by mphalliday** [comment]
@VicVol I'm so happy it worked for you! 

No other changes come to mind.  But we are constantly improving our API.  Do be sure to join our google group at https://groups.google.com/a/redguava.com.au/forum/#!topic/cliniko-api

Also just make sure to always set the correct `content_type` and `accept` headers on each request ... Funny things can start happening without the correct headers and format.  I haven't used RestClient before, but I would assume there should be a way to set a default set of headers, so that you don't have to do it with each request!

Cheers!
Michael.
