### ISSUE TITLE
Expose extra info for practitioners

### ISSUE THREAD

**Issue by jaesoonis** [redguava/cliniko-api#76]
Hey Team

Is there a way to retrieve the sidebar information from a practitioner as shown in the image below?

http://puu.sh/gCn3Y/10a0329320.png

We would like to use the "Type", "Number" and "Description" field to hold onto additional detail about the practitioner.

Thanks

Regards

Jae Soon

**Comment by bart3k** [comment]
Hi Jae, 

We have just released an update which exposing all the details you were looking for.  Please let us know if you have any questions. 

Regards,
Bartosz
