### ISSUE TITLE
Add API definition to Mashape

### ISSUE THREAD

**Issue by antoinelamy** [redguava/cliniko-api#89]
It would be very nice if the API documentation could be added to Mashape. I would enable fast integration using Unirest universal REST API framework in 8 different languages.

**Comment by jfriedlaender** [comment]
I looked at the website, I don't really understand what it does.  How would it help you if we had our API there?

**Comment by antoinelamy** [comment]
Mainly fast client side integration by generating data layer objects, network and authentication code in 8 different programming languages. Plus, if the documentation was available in a standard format like swagger, it would allow the use of a documentation tool right inside IDEs.
