### ISSUE TITLE
Populating the referrer for patients [get] 

### ISSUE THREAD

**Issue by JonnyBoxall** [redguava/cliniko-api#93]
Hi, is the referral source going to be included soon in the cliniko API export of patient records? I have a pressing business need for this information. Even if it was just the string from the top level referrer, this would be sufficient to allow me to export the required information.

For any kind of marketing impact monitoring having the referral source is vital. This will allow clients to analyse the effect of specific marketing initiatives. In my case I am paying commission to a vendor based on patient referrals which is only payable when patients book appointments with certain practitioners. As you can imagine calculating the payable amount is extremely difficult with the standard reporting in cliniko. I need to produce the report over the next couple of weeks.

Because the need is acute, would it be possible to raise the priority of this update? I am sure many clients would benefit from it's swift inclusion in the API.

Many thanks - Jonathan

**Comment by Andrewche55** [comment]
This would be great for our business marketing analytics too.

**Comment by hagen** [comment]
Referral source can be found on `GET /patients/:id/referral_source`.
Any referral source note is available on `/patients/:id` however.
