### ISSUE TITLE
Importing messages delivered from other practices

### ISSUE THREAD

**Issue by lairyaus** [redguava/cliniko-api#94]
Looking at the API I can't see any provisioning for message delivery.

Would it be possible to add an option to import results delivered to a practice?

My company works with HL7 2.3.1 format files but could export to XML or similar if required.

This would facilitate pathology and radiology providers sending reports in electronic form. Additonally referrals from other medical practices could be delivered as well.

**Comment by jfriedlaender** [comment]
We don't really have a place for messages in our app.  Where would you put them? How would you see it working in Cliniko?

Any more detail on what you would like would help.

**Comment by lairyaus** [comment]
I was assuming that Letters or Treatment Notes that were generated in the software were also stored against their prospective patient. Could incoming results for a patient be stored in the same location?

**Comment by hagen** [comment]
Closing due to age. Please reopen if required.
