### ISSUE TITLE
Provide link to replacement patient if a patient deletion is a result of a merge

### ISSUE THREAD

**Issue by nicholasmott** [redguava/cliniko-api#97]
When merging a patient in Cliniko all detail is copied to one patient and the other is (presumably) deleted.

The deleted patient should appear on the deleted patients end point but there is no information that the information related to this patient should actually be merged into another patient record.

It would be great if a link could appear on the deleted patients end point which indicated that this deletion was the result of a merge and which patient record was the destination of the merge.

This would allow us to keep patient records in sync with Cliniko much more effectively.

**Comment by jfriedlaender** [comment]
Thanks for this, we'll have a think how to handle it best and see what we can do.

I'm don't think anyone is free to get to it right away though.

**Comment by nicholasmott** [comment]
Hey chaps,

It's been a while and wondering if you had a view on this.

At the moment, if a deletion comes from Cliniko we have to set it into a temporary state and then ask our customers if it should be merged in our system. Effectively they have to do the merge process twice, once in Cliniko and then again in Instinctive Notes.

If you could set a link on the deleted patient back to the remaining patient they were merged into then we could deal with this seamlessly in the background.

WDYT.

**Comment by bpinto** [comment]
It's something we need as well, but we haven't yet worked on it. =/

Thanks for reminding us about it.

**Comment by bpinto** [comment]
Hi @nicholasmott we are going to add this merged information to the merged patient in the next days.

On a second note, merged patients are not deleted but archived.

**Comment by nicholasmott** [comment]
Awesome. I'll keep an eye out.

**Comment by nicholasmott** [comment]
Hi Team,

Any further update on this? It would remove a great deal of confusion between Cliniko and Instinctive Notes for our joint customers and get rid of a whole heap of manual tasks.

**Comment by bpinto** [comment]
Hey @nicholasmott while we don't have a link to the merged patient we have added an attribute named `merged` that will contain who the patient was merged with (mergedWithId) and when (mergedAt).

**Comment by nicholasmott** [comment]
That will be perfect. I'll look out for the update.

**Comment by bpinto** [comment]
@nicholasmott well, we changed how the information is displayed to be consistent with the rest of the API. You can see the structure of the information on #247.

**Comment by nicholasmott** [comment]
This is awesome. Nice to knock off an old issue too 😀.
