### ISSUE TITLE
Question regarding filtering query results by updated_at. 

### ISSUE THREAD

**Issue by TM818** [redguava/cliniko-api#98]
We're attempting to filter query results by updated_at, and we want to confirm the best way to do so. Currently, the syntax for our API call is this (in this example, all patients updated at or after 2015-10-17, 11:00:11): 

  https://#{OUR_API_KEY}@api.cliniko.com/v1/patients?q[]=updated_at:>=2015-10-17T11:0:11Z&page=1

  Our software then detects for the presence of a ["links"]["next"] field in the parsed response, and if there is one, it increments the "page" number to 2 and runs the same query again ending with &page=2, then &page=3, and so forth until ["links"]["next"] in the parsed response is nil. 

  Is this the proper way to go about returning all possible pages of results for a filtered Cliniko API query?

**Comment by JohnColvin** [comment]
Hello!

Your paging approach should work. Our recommended way, though, is to use the next link URL to fetch the next page, rather than incrementing the page parameter yourself. The next link will retain your filter parameters, but it won't retain the API key at the beginning of the URL. We recommend [passing the authorization header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basic_access_authentication#Client_side) instead of sending it on the URL.

This is all just semantics, though. If there's a reason that you need to send the key on the URL or increment the page parameter yourself, it should work as you describe.

**Comment by TM818** [comment]
Thank you John. Quick follow-up question: if you notice, in the URL syntax provided, the datetime is "2015-10-17T11:0:11", where 11:00:11 is represented as 11:0:11. Does it matter to Cliniko's API if any of the datetime fields are 0 instead of 00? Will a single zero for a field (such as hour, minute, or second) work properly?

**Comment by JohnColvin** [comment]
The single zero is currently interpreted correctly. I can't guarantee that we won't make a change in the future that would break that, though. The ISO 8601 standard only supports padded hours, minutes, and seconds. http://www.w3.org/TR/NOTE-datetime

Also of note :wink: https://xkcd.com/1179/

**Comment by TM818** [comment]
Haha, very nice. Thank you.

**Comment by TM818** [comment]
John, quick follow-up question regarding this. We're converting our code to use the Authorization header instead of passing the API key in the URL as you recommended, but the link you provided specifies to Base64 encode "Basic username:password". We use this process with other oauth2-based API providers, but they have us Base64 encode the API CLIENT_ID and CLIENT_SECRET, for example, "Basic CLIENT_ID:CLIENT_SECRET". Cliniko, last we checked, does not support oauth2 and individual ClientIDs / Client Secrets. 

Therefore, are you saying that, when we create the authorization header for Cliniko, we should use the Cliniko email address as the username, and the API key as the password? Otherwise, we would have to instruct all of our users to update their profiles for our app and add their Cliniko account password (instead of the API key) which we would rather not do.
