### ISSUE TITLE
Get available times is returning local time

### ISSUE THREAD

**Issue by nickbwsp** [redguava/cliniko-api#99]
I have set up a user in perth which has an offset of +8, and when I make a call to get available times it is returning the times as UTC even though they are Local.

What I am getting: "2015-10-26T09:00:00Z" (Local time but returned as UTC)
What I should be getting: "2015-10-26T09:00:00+8:00" or its utc equivalent which takes into account the offset "2015-10-26T01:00:00".

**Comment by JohnColvin** [comment]
Hi Nick,

Our API always returns times in UTC. You'll need to localize on your end. Our [user endpoints](https://github.com/redguava/cliniko-api/blob/master/sections/users.md) return the user's time zone.

However, we don't think that a per user time zone is the best way to handle localization any longer. We intend to remove this from Cliniko and replace it with a time zone setting per business. We will continue to serve the time zone on the user endpoint, though. When we make this switch, we will serve the account time zone as the user time zone.

**Comment by nickbwsp** [comment]
Thanks for getting back to me so quickly John, I have done a little bit of testing and I still think there might be something wrong: I changed the time zone for a clinician from the Perth to Samoa, and each time I called the API I got the same results ("2015-10-26T09:00:00Z), if they are being returned in UTC the results should be different, it looks like it returning in local time ignoring the offset as far as I can tell.

**Comment by jfriedlaender** [comment]
Hi Nick,

You save it in UTC, we store it in UTC, we return it in UTC.

It won't matter what time zone the user is, the appointment still occurs at a real point in time.  If they're using Cliniko, the time we display it to them as will be affected by their time zone.

For example, if they were in Melbourne, Australia, it might show as 10am.  If they are in Perth, Australia, it could show as 8am.  It's still the same time in UTC in the database though.

Does that make sense?

Joel

**Comment by nickbwsp** [comment]
Cheers Joel, that makes sense the appointments are in UTC, the one thing that doesn't make sense to me is that if I set the availability for a clinician in perth time from 9am for the 2015-10-26, when I retrieve available times, at the moment I get 2015-10-26T09:00:00Z this isn't UTC (AFAIK) this is the local time in Perth for the clinician, shouldn't it be  2015-10-26T01:00:00Z (ie 8 hours behind for UTC)? I may be misunderstanding this so I apologise in advance.

**Comment by michaelspooner** [comment]
Hello Cliniko,

When we invoke the Get Available Times API, we are not seeing the expected times in UTC.
I just want to further explain the issue Nick and our team are seeing.

We have set our account to Sydney time
We have created a practitioner in Perth, available 9am - 11am on Mondays.
Calling the Get Available Times returns for a single day (2015-10-26) returns the following
2015-10-25T22:00:00Z
2015-10-25T22:40:00Z
2015-10-25T23:20:00Z

The above times converted to Sydney are
2015-10-26 09:00 +11, 2015-10-26 09:40 +11, 2015-10-26 10:20 +11

The above times converted to Perth are
2015-10-26 07:00 +8, 2015-10-26 07:40 +8, 2015-10-26 08:20 +8

As you can see the UTC dates from the API converted to Perth local time are not correct for the Practitioner.

We expected to see UTC dates as 
2015-10-25T01:00:00Z --> 9am Perth, 12pm Sydney
2015-10-25T01:40:00Z --> 9:40am Perth, 12:40 Sydney
2015-10-25T02:20:00Z --> 10:20am Perth, 1:20pm Sydney

I can email our fiddler test calls in a text file if you want to see more evidence?

**Comment by nickbwsp** [comment]
As michael said it appears that the clinician's timezone is completely ignored and all times are in the timezone of the account which is why when I changed timezones for the clinician it always returned the same thing. 

The issue is then when a clinician looks at their calendar to set their availability and they have their timezone configured to something other than what the account is configured to, then they must make sure they convert their availability to the account's time zone, which is obviously not clear given they have their time zone set.

**Comment by JohnColvin** [comment]
Sorry about the delay in responding here. When I originally responded, I had forgotten that available times uses local time. The rest of our API uses UTC. You're correct in the behavior described: in settings, the available times are interpreted in the practitioner's time zone, but on this endpoint they are interpreted in the account's time zone.

We recommend that you keep the account and practitioner time zones the same. We've decided that handling time zones per user is not the best way to do things. We plan to remove the user time zone option from Cliniko and replace it with a time zone per business. I'm not sure when we'll be able to do that, though.
